import {beforeEach,describe,expect,it,vi} from 'vitest';
import {render,screen,waitFor} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {ConsoleApp} from '../src/app';
import type {Session} from '../src/types';

const operatorSession:Session={user:{id:'u1',email:'ops@example.com',name:'Operator'},workspace:{id:'w1',name:'Production'},role:'operator',permissions:['endpoint:read','endpoint:create','endpoint:start','node:read','operation:read','audit:read','workspace:read'],capabilities:{operations:['create','start'],providers:{fake:{enabled:true},napcat:{enabled:false,reason:'License required'}}}};
const adminSession:Session={...operatorSession,role:'admin',permissions:[...operatorSession.permissions,'node:create','member:read','member:manage','credential:read','credential:manage','settings:read','settings:manage']};
const viewerSession:Session={...operatorSession,role:'viewer',permissions:['endpoint:read','node:read','provider:read','operation:read','audit:read','workspace:read'],capabilities:{...operatorSession.capabilities,operations:[]}};
const endpoints={items:[{id:'ep1',name:'Primary fake',providerId:'fake',node:{id:'n1',name:'edge-1'},status:{node:'online',runtime:'ready',provider:'available',protocol:'connected',convergence:'converged'},activeOperationId:null}],page:1,pageSize:25,total:1};
function mockApi(auth=true,session=operatorSession){return vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>{const url=String(input); if(url.endsWith('/auth/csrf'))return new Response(JSON.stringify({csrfToken:'csrf'})); if(url.endsWith('/auth/login'))return new Response(JSON.stringify({ok:true})); if(url.endsWith('/auth/session'))return new Response(auth?JSON.stringify(session):'',{status:auth?200:401}); if(url.endsWith('/nodes'))return new Response(JSON.stringify({items:[],page:1,pageSize:25,total:0})); if(url.endsWith('/endpoints'))return new Response(JSON.stringify(endpoints)); if(url.endsWith('/endpoints/ep1'))return new Response(JSON.stringify(endpoints.items[0])); if(url.endsWith('/operations/op1'))return new Response(JSON.stringify({id:'op1',endpointId:'ep1',action:'start',status:'succeeded',generation:1})); if(url.endsWith('/workspaces/current/summary'))return new Response(JSON.stringify({endpoints:1,operations:0})); if(url.endsWith('/workspaces/current/settings/resend'))return new Response(JSON.stringify({enabled:true,recipient:'ops@example.com',from:'Botroost <alerts@example.com>',graceSeconds:180,apiKeyConfigured:true})); if(url.includes('/workspaces/current/')&&!session.permissions.some(permission=>url.includes('members')?permission==='member:read':url.includes('credentials')?permission==='credential:read':url.includes('settings')?permission==='settings:read':true))return new Response('',{status:403}); if(init?.method==='POST'||init?.method==='PUT')return new Response(JSON.stringify(url.endsWith('/settings/resend')?{enabled:true,recipient:'ops@example.com',from:'Botroost <alerts@example.com>',graceSeconds:240,apiKeyConfigured:true}:{id:'created'}),{status:init?.method==='POST'?201:200}); return new Response(JSON.stringify({items:[],page:1,pageSize:25,total:0}));});}
beforeEach(()=>{history.replaceState({},'', '/');});
describe("ConsoleApp",()=>{
  it("presents the product as a cloud-native OneBot endpoint cluster console",async()=>{
    vi.stubGlobal('fetch',mockApi(true));render(<ConsoleApp/>);
    expect((await screen.findAllByText('OneBot Cluster')).length).toBeGreaterThan(0);
    expect(screen.getByText('Cloud-native OneBot endpoint cluster console')).toBeInTheDocument();
  });
 it('redirects unauthenticated users to login with returnTo',async()=>{vi.stubGlobal('fetch',mockApi(false));render(<ConsoleApp/>);expect(await screen.findByRole('heading',{name:'Sign in'})).toBeVisible();expect(location.pathname+location.search).toContain('/login?returnTo=');});
 it('logs out and navigates to the sign-in route',async()=>{const f=mockApi(true);vi.stubGlobal('fetch',f);render(<ConsoleApp/>);expect(await screen.findByText('Cloud-native OneBot endpoint cluster console')).toBeVisible();await userEvent.click(screen.getByRole('button',{name:'Log out'}));expect(await screen.findByRole('heading',{name:'Sign in'})).toBeVisible();expect(location.pathname).toBe('/login');});
 it('submits login then loads the authenticated session',async()=>{const f=mockApi(true);vi.stubGlobal('fetch',f);history.replaceState({},'','/login');render(<ConsoleApp/>);await userEvent.type(await screen.findByLabelText(/Email/),'ops@example.com');await userEvent.type(screen.getByLabelText(/Password/),'password');await userEvent.click(screen.getByRole('button',{name:'Sign in'}));expect(await screen.findByText('Cloud-native OneBot endpoint cluster console')).toBeVisible();});
 it('renders product-specific navigation against the formal overview contract',async()=>{vi.stubGlobal('fetch',mockApi());render(<ConsoleApp/>);expect(await screen.findByText('Cloud-native OneBot endpoint cluster console')).toBeVisible();for(const name of ['Protocol endpoints','Agent nodes','Changes','Audit'])expect(screen.getByRole('link',{name})).toBeVisible();expect(screen.queryByRole('link',{name:'Runtime drivers'})).not.toBeInTheDocument();});
 it('renders empty state',async()=>{vi.stubGlobal('fetch',mockApi());history.replaceState({},'','/nodes');render(<ConsoleApp/>);expect(await screen.findByText('No nodes found')).toBeVisible();});
 it('renders 404 route state',async()=>{vi.stubGlobal('fetch',mockApi());history.replaceState({},'','/does-not-exist');render(<ConsoleApp/>);expect(await screen.findByText('Page not found')).toBeVisible();});
 it('shows five endpoint status layers and license gate',async()=>{vi.stubGlobal('fetch',mockApi());history.replaceState({},'','/endpoints');render(<ConsoleApp/>);expect(await screen.findByText('Primary fake')).toBeVisible();for(const state of ['online','ready','available','connected','converged'])expect(screen.getByText(state)).toBeVisible();await userEvent.click(screen.getByRole('button',{name:'Create endpoint'}));expect(screen.getByText('NapCat')).toBeVisible();expect(screen.getByRole('button',{name:/NapCat/})).toBeDisabled();expect(screen.getByText('License required')).toBeVisible();});
 it('never renders enrollment token outside its one-time modal',async()=>{const f=mockApi(true,adminSession);f.mockImplementation(async(input)=>{const url=String(input);if(url.endsWith('/auth/session'))return new Response(JSON.stringify(adminSession));if(url.endsWith('/nodes'))return new Response(JSON.stringify({items:[{id:'n1',name:'edge-1',provider:'fake',lastHeartbeatAt:new Date().toISOString()}],page:1,pageSize:25,total:1}));if(url.endsWith('/auth/csrf'))return new Response(JSON.stringify({csrfToken:'csrf'}));if(url.endsWith('/nodes/enrollment-tokens'))return new Response(JSON.stringify({token:'secret-once'}));return new Response('{}');});vi.stubGlobal('fetch',f);history.replaceState({},'','/nodes');render(<ConsoleApp/>);await userEvent.click(await screen.findByRole('button',{name:'Generate enrollment token'}));expect(await screen.findByText('secret-once')).toBeVisible();await userEvent.click(screen.getByRole('button',{name:'Close'}));await waitFor(()=>expect(screen.queryByText('secret-once')).not.toBeInTheDocument());});
 it('shows workspace subnav and guards sensitive routes by permissions',async()=>{vi.stubGlobal('fetch',mockApi(true,viewerSession));history.replaceState({},'','/workspace/members');render(<ConsoleApp/>);expect(await screen.findByText('Page not found')).toBeVisible();expect(screen.queryByRole('link',{name:'Workspace'})).not.toBeInTheDocument();});
 it('renders workspace subnav for admins',async()=>{vi.stubGlobal('fetch',mockApi(true,adminSession));history.replaceState({},'','/workspace/credentials');render(<ConsoleApp/>);expect(await screen.findByRole('heading',{name:'Credentials'})).toBeVisible();for(const name of ['Members','Credentials','Settings'])expect(screen.getByRole('link',{name})).toBeVisible();});
 it('configures Resend without revealing the API key and can queue a test email',async()=>{const f=mockApi(true,adminSession);vi.stubGlobal('fetch',f);history.replaceState({},'','/workspace/settings');render(<ConsoleApp/>);expect(await screen.findByRole('heading',{name:'Email alerts'})).toBeVisible();expect(screen.getByText('API key configured')).toBeVisible();expect(screen.queryByDisplayValue(/re_/)).not.toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:'Save'}));await waitFor(()=>expect(f.mock.calls.some(([input,init])=>String(input).endsWith('/settings/resend')&&init?.method==='PUT')).toBe(true));await userEvent.click(screen.getByRole('button',{name:'Send test email'}));await waitFor(()=>expect(f.mock.calls.some(([input])=>String(input).endsWith('/settings/resend/test'))).toBe(true));});
 it('warns about active operations and disables conflicting endpoint actions',async()=>{const active={...endpoints.items[0],activeOperationId:'op1'};const f=mockApi();f.mockImplementation(async(input)=>{const url=String(input);if(url.endsWith('/auth/session'))return new Response(JSON.stringify(operatorSession));if(url.endsWith('/endpoints/ep1'))return new Response(JSON.stringify(active));return mockApi()(input);});vi.stubGlobal('fetch',f);history.replaceState({},'','/endpoints/ep1');render(<ConsoleApp/>);expect(await screen.findByText('Operation in progress')).toBeVisible();expect(screen.getByRole('button',{name:'Start'})).toBeDisabled();});
 it('refetches endpoint detail and list from completed operation detail',async()=>{const f=mockApi();vi.stubGlobal('fetch',f);history.replaceState({},'','/operations/op1');render(<ConsoleApp/>);expect(await screen.findByText('Operation detail')).toBeVisible();await waitFor(()=>expect(f.mock.calls.filter(([input])=>String(input).endsWith('/endpoints/ep1')).length).toBeGreaterThan(0));await waitFor(()=>expect(f.mock.calls.filter(([input])=>String(input).endsWith('/endpoints')).length).toBeGreaterThan(0));});
 it('only exposes endpoint rename until configuration API exists',async()=>{vi.stubGlobal('fetch',mockApi(true,{...operatorSession,capabilities:{...operatorSession.capabilities,configurationSchemas:{fake:[{key:'apiKey',label:'API key',type:'string'}]}}}));history.replaceState({},'','/endpoints/ep1');render(<ConsoleApp/>);expect(await screen.findByRole('heading',{name:'Primary fake'})).toBeVisible();expect(screen.queryByLabelText('API key')).not.toBeInTheDocument();expect(screen.getByRole('button',{name:'Rename'})).toBeVisible();});
});
