import {beforeEach,describe,expect,it,vi} from 'vitest';
import {render,screen,waitFor} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {ConsoleApp} from '../src/app';

const session={user:{id:'u1',email:'ops@example.com',name:'Operator'},workspace:{id:'w1',name:'Production'},permissions:['endpoint:read','endpoint:create','endpoint:start','node:read','operation:read','audit:read','workspace:read'],capabilities:{operations:['create','start'],providers:{fake:{enabled:true},napcat:{enabled:false,reason:'License required'}}}};
const endpoints={items:[{id:'ep1',name:'Primary fake',providerId:'fake',nodeId:'n1',status:{node:'online',runtime:'ready',provider:'available',protocol:'connected',convergence:'converged'},activeOperationId:null}],page:1,pageSize:25,total:1};
function mockApi(auth=true){return vi.fn(async(input:RequestInfo|URL)=>{const url=String(input); if(url.endsWith('/auth/csrf'))return new Response(JSON.stringify({token:'csrf'})); if(url.endsWith('/auth/login'))return new Response(JSON.stringify({ok:true})); if(url.endsWith('/auth/session'))return new Response(auth?JSON.stringify(session):'',{status:auth?200:401}); if(url.endsWith('/endpoints'))return new Response(JSON.stringify(endpoints)); if(url.endsWith('/overview'))return new Response('',{status:404}); return new Response(JSON.stringify({items:[],page:1,pageSize:25,total:0}));});}
beforeEach(()=>{history.replaceState({},'', '/');});
describe('ConsoleApp',()=>{
 it('redirects unauthenticated users to login with returnTo',async()=>{vi.stubGlobal('fetch',mockApi(false));render(<ConsoleApp/>);expect(await screen.findByRole('heading',{name:'Sign in'})).toBeVisible();expect(location.pathname+location.search).toContain('/login?returnTo=');});
 it('submits login then loads the authenticated session',async()=>{const f=mockApi(true);vi.stubGlobal('fetch',f);history.replaceState({},'','/login');render(<ConsoleApp/>);await userEvent.type(await screen.findByLabelText(/Email/),'ops@example.com');await userEvent.type(screen.getByLabelText(/Password/),'password');await userEvent.click(screen.getByRole('button',{name:'Sign in'}));expect(await screen.findByText('Operational overview')).toBeVisible();});
 it('renders dense navigation and unavailable API gaps without fake success',async()=>{vi.stubGlobal('fetch',mockApi());render(<ConsoleApp/>);expect(await screen.findByText('Operational overview')).toBeVisible();expect(await screen.findByText('Unavailable')).toBeVisible();for(const name of ['Endpoints','Nodes','Providers','Operations','Audit','Workspace'])expect(screen.getByRole('link',{name})).toBeVisible();});
 it('renders empty state',async()=>{vi.stubGlobal('fetch',mockApi());history.replaceState({},'','/nodes');render(<ConsoleApp/>);expect(await screen.findByText('No nodes found')).toBeVisible();});
 it('renders 404 route state',async()=>{vi.stubGlobal('fetch',mockApi());history.replaceState({},'','/does-not-exist');render(<ConsoleApp/>);expect(await screen.findByText('Page not found')).toBeVisible();});
 it('shows five endpoint status layers and license gate',async()=>{vi.stubGlobal('fetch',mockApi());history.replaceState({},'','/endpoints');render(<ConsoleApp/>);expect(await screen.findByText('Primary fake')).toBeVisible();for(const state of ['online','ready','available','connected','converged'])expect(screen.getByText(state)).toBeVisible();await userEvent.click(screen.getByRole('button',{name:'Create endpoint'}));expect(screen.getByText('NapCat')).toBeVisible();expect(screen.getByRole('button',{name:/NapCat/})).toBeDisabled();expect(screen.getByText('License required')).toBeVisible();});
 it('never renders enrollment token outside its one-time modal',async()=>{const f=mockApi();f.mockImplementation(async(input)=>{const url=String(input);if(url.endsWith('/auth/session'))return new Response(JSON.stringify(session));if(url.endsWith('/nodes'))return new Response(JSON.stringify({items:[{id:'n1',name:'edge-1',state:'online'}],page:1,pageSize:25,total:1}));if(url.endsWith('/auth/csrf'))return new Response(JSON.stringify({token:'csrf'}));if(url.endsWith('/nodes/enrollment-token'))return new Response(JSON.stringify({token:'secret-once'}));return new Response('{}');});vi.stubGlobal('fetch',f);history.replaceState({},'','/nodes');render(<ConsoleApp/>);await userEvent.click(await screen.findByRole('button',{name:'Generate enrollment token'}));expect(await screen.findByText('secret-once')).toBeVisible();await userEvent.click(screen.getByRole('button',{name:'Close'}));await waitFor(()=>expect(screen.queryByText('secret-once')).not.toBeInTheDocument());});
});
