import {useCallback,useEffect,useRef,useState} from 'react';import {api} from './api';import {startCompletionPoller} from './polling';
const POLL_TIMEOUT_MS=10_000;
export function useApi<T>(path:string,interval?:number|((data:T|undefined)=>number|undefined),enabled=true){
 const[data,setData]=useState<T>();const[error,setError]=useState<Error>();const[loading,setLoading]=useState(enabled);const dataRef=useRef<T|undefined>(undefined);const intervalRef=useRef(interval);intervalRef.current=interval;
 const refresh=useCallback(async()=>{if(!enabled)return;try{const next=await api.get<T>(path);dataRef.current=next;setData(next);setError(undefined)}catch(e){setError(e as Error)}finally{setLoading(false)}},[path,enabled]);
 useEffect(()=>{if(!enabled){setLoading(false);return}let disposed=false;let controller:AbortController|undefined;const run=async()=>{controller=new AbortController();const timeout=setTimeout(()=>controller?.abort(new DOMException('Request timed out','TimeoutError')),POLL_TIMEOUT_MS);try{const next=await api.get<T>(path,{signal:controller.signal});if(!disposed){dataRef.current=next;setData(next);setError(undefined)}}catch(cause){if(!disposed)setError(cause as Error)}finally{clearTimeout(timeout);if(!disposed)setLoading(false)}};const stop=startCompletionPoller(run,()=>{const current=intervalRef.current;return typeof current==='function'?current(dataRef.current):current});return()=>{disposed=true;stop();controller?.abort(new DOMException('Request cancelled','AbortError'))}},[path,enabled]);
 return{data,error,loading,refresh,setData}
}
export function usePath(){const [path,setPath]=useState(location.pathname+location.search);useEffect(()=>{const fn=()=>setPath(location.pathname+location.search);addEventListener('popstate',fn);return()=>removeEventListener('popstate',fn)},[]);return path}
