import {useEffect,useRef,useState,type ReactNode} from 'react';import {RefreshCw} from 'lucide-react';import {QRCodeSVG} from 'qrcode.react';import {api} from './api';import {ENDPOINTS_CHANGED} from './app';import {useApi} from './hooks';import {useI18n,type MessageKey} from './i18n';import {actionAvailability,nodeConnectionStatus,statusLayers} from './policy';import {SchemaForm} from './schema-form';import {Empty,Failure,Loading} from './states';import type {ActiveOperation,AlertSettings,AuditEvent,Endpoint,Member,Node,NotificationTarget,Operation,Page,Provider,SchemaField,Session} from './types';import {Badge,Button,Card,Input,Link,Modal,PageHeading,Select,Stack,Table,navigate} from './ui';import {Tabs,TabsContent,TabsList,TabsTrigger} from './components/tabs';import {WebSocketConnectionEditor,type WsClient,type WsServer} from './websocket-editor';
import {trafficDisplayStatus,type TrafficFreshness} from './traffic-status';
import {DirectoryTable} from './directory-table';
const State=<T,>({q,children}:{q:ReturnType<typeof useApi<T>>;children:(x:T)=>ReactNode})=>q.loading?<Loading/>:q.error?<Failure error={q.error}/>:children(q.data!);
const Info=({label,children}:{label:string;children:ReactNode})=><div className="info"><small>{label}</small><div>{children}</div></div>;
type ProgressOperation=Pick<Operation,'id'|'action'|'status'|'progress'>|ActiveOperation;
const endpointPollInterval=(data:Endpoint|undefined)=>data?.activeOperation?1000:5000;
const operationListPollInterval=(data:Page<Operation>|undefined)=>data?.items.some(operation=>['queued','running'].includes(operation.status))?1000:5000;
const activityTitle=(t:(key:MessageKey)=>string,operation:ProgressOperation)=>operation.status==='succeeded'?t('endpoints.completed'):operation.status==='failed'||operation.status==='stale'?t('operation.failed'):operation.action==='start'?t('operation.starting'):operation.action==='restart'?t('operation.restarting'):operation.action==='stop'?t('operation.stopping'):operation.action==='delete'?t('operation.deleting'):t('operation.applying');
function OperationProgressView({operation,compact=false}:{operation:ProgressOperation;compact?:boolean}){const{t,locale}=useI18n();const progress=operation.progress,active=operation.status==='queued'||operation.status==='running';const body=<div className={`operation-progress${compact?' compact':''}`} role={active?'status':undefined} aria-live={active?'polite':undefined} aria-label={activityTitle(t,operation)}><div className="operation-progress-heading"><div className="operation-progress-title">{active?<span className="activity-pulse" aria-hidden="true"/>:null}<strong>{activityTitle(t,operation)}</strong></div><Badge good={operation.status==='succeeded'}>{progress.percent}%</Badge></div><progress max="100" value={progress.percent} aria-label={t('operation.progress')}/><div className="operation-progress-copy"><span>{progress.message}</span>{compact?null:<small className="muted">{t('operation.stage',{phase:progress.phase.replaceAll('-',' '),time:new Date(progress.updatedAt).toLocaleTimeString(locale)})}</small>}</div>{compact?null:<Link to={`/operations/${operation.id}`}>{t('operation.viewDetails')}</Link>}</div>;return compact?body:<Card className="operation-progress-card">{body}</Card>}
export function Overview(){const{t}=useI18n();const q=useApi<{endpoints:number;operations:number}>('/workspaces/current/summary');return <Stack><PageHeading title={t('nav.cluster')} description={t('overview.description')}/><State q={q}>{d=><div className="summary-grid"><Card><span className="muted">{t('overview.protocolEndpoints')}</span><strong className="summary-value">{d.endpoints}</strong><small>{t('overview.managedServices')}</small></Card><Card><span className="muted">{t('overview.changes')}</span><strong className="summary-value">{d.operations}</strong><small>{t('overview.recordedOperations')}</small></Card></div>}</State></Stack>}
export function Endpoints({session,q}:{session:Session;q:ReturnType<typeof useApi<Page<Endpoint>>>}){
 const{t}=useI18n();
 const nodes=useApi<Page<Node>>('/nodes');
 const[open,setOpen]=useState(false),[provider,setProvider]=useState(''),[nodeId,setNodeId]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>();
 const fields:SchemaField[]=[{key:'name',label:t('endpoints.colName'),type:'string',required:true},...(provider?session.capabilities.configurationSchemas?.[provider]??[]:[])];
 async function create(values:Record<string,unknown>){setBusy(true);setError(undefined);try{const ep=await api.mutate<Endpoint>('/endpoints',{providerId:provider,nodeId,...values});dispatchEvent(new Event(ENDPOINTS_CHANGED));navigate(`/endpoints/${ep.id}`)}catch(e){setError(e)}finally{setBusy(false)}}
 const closeCreate=()=>{if(busy)return;setOpen(false);setProvider('');setNodeId('');setError(undefined)};
 if(q.loading||nodes.loading)return <Loading/>;if(q.error||nodes.error)return <Failure error={q.error??nodes.error}/>;
 const canCreate=actionAvailability('create',{permissions:session.permissions,capabilities:session.capabilities,activeOperationId:null}).visible;
 return <Stack>
  <PageHeading kicker={t('endpoints.kicker')} title={t('endpoints.title')} description={t('endpoints.description')} action={<div className="page-heading-actions"><Button variant="outline" aria-label={t('endpoints.refreshStatus')} disabled={q.refreshing} onClick={()=>void q.refresh()}><RefreshCw className={q.refreshing?'refresh-spin':undefined}/>{q.refreshing?t('common.refreshing'):t('common.refresh')}</Button>{canCreate?<Button onClick={()=>setOpen(true)}>{t('endpoints.create')}</Button>:null}</div>}/>
  {q.data!.items.length===0?<Empty name={t('endpoints.empty')}/>:<Table headers={[t('endpoints.colName'),t('endpoints.colProvider'),t('endpoints.colNode'),t('endpoints.colActivity'),t('endpoints.colNodeStatus'),t('endpoints.colRuntime'),t('endpoints.colProviderStatus'),t('endpoints.colProtocol'),t('endpoints.colConvergence')]} rows={q.data!.items.map(ep=>[<Link to={`/endpoints/${ep.id}`}>{ep.name}</Link>,ep.providerId,ep.node?.name??t('common.unassigned'),ep.activeOperation?<OperationProgressView operation={ep.activeOperation} compact/>:<span className="muted">{t('common.idle')}</span>,...statusLayers(ep.status).map(x=><Badge good={['connected','online','ready','available','converged'].includes(x.value)}>{x.value}</Badge>)])}/>}
  <Modal open={open} onClose={closeCreate} title={provider?t('endpoints.configure'):t('endpoints.create')} description={provider?t('endpoints.chooseNode',{provider:provider==='napcat'?t('endpoints.napcat'):provider}):t('endpoints.chooseProvider')} footer={provider?<><Button type="button" variant="outline" disabled={busy} onClick={()=>{setProvider('');setNodeId('');setError(undefined)}}>{t('common.back')}</Button><Button type="submit" form="create-endpoint-form" busy={busy} disabled={!nodeId}>{t('endpoints.create')}</Button></>:<Button variant="outline" onClick={closeCreate}>{t('common.cancel')}</Button>}>
    {!provider?<div className="provider-picker">{Object.entries(session.capabilities.providers??{}).map(([providerId,gate])=>{const label=providerId==='napcat'?t('endpoints.napcat'):providerId==='fake'?t('endpoints.fake'):providerId;return <button type="button" className="provider-choice" key={providerId} disabled={!gate.enabled} onClick={()=>{setProvider(providerId);setError(undefined)}}><span><strong>{label}</strong><small>{providerId==='napcat'?t('endpoints.napcatHint'):t('endpoints.providerHint')}</small></span><Badge good={gate.enabled}>{gate.enabled?t('common.available'):t('common.unavailable')}</Badge>{gate.reason?<small className="provider-reason">{gate.reason}</small>:null}</button>})}</div>:<Stack><Select label={t('endpoints.node')} required value={nodeId} onChange={e=>setNodeId(e.currentTarget.value)}><option value="">{t('endpoints.selectNode')}</option>{nodes.data!.items.filter(n=>n.provider===provider).map(n=><option value={n.id} key={n.id}>{n.name}</option>)}</Select><SchemaForm key={provider} formId="create-endpoint-form" fields={fields} submitLabel={t('endpoints.create')} showSubmit={false} busy={busy} onSubmit={v=>{if(nodeId)void create(v)}}/>{error?<Failure error={error}/>:null}</Stack>}
  </Modal>
 </Stack>;
}
type OneBotProbe={ok:boolean;durationMs:number;error:string|null};
type OneBotDirectoryCollection={count:number;items:Record<string,unknown>[];truncated:boolean;observedAt:string|null;probe:OneBotProbe};
type TrafficWindow={inbound:number;outbound:number;total:number;bytes:number};
type TrafficEvent={at:string;direction:'inbound'|'outbound';scope:'group'|'private'|'unknown';bytes:number};
type ConnectionEvent={at:string;transport:'websocket-client'|'websocket-server';status:'listening'|'connected'|'disconnected'|'reconnecting'|'error'};
type ProtocolTraffic={status:'ok'|'partial'|'unavailable';complete?:boolean;source:string;privacy:'aggregate_only';observedAt:string;sampleIntervalSeconds:number;oneMinute:TrafficWindow;fiveMinutes:TrafficWindow;buckets:{startedAt:string;inbound:number;outbound:number;total:number}[];recent:TrafficEvent[];recentConnections:ConnectionEvent[];error?:string};
type NapCatStatus={qq:null|Record<string,unknown>;onebot:null|{status?:Record<string,unknown>;loginInfo?:Record<string,unknown>;version?:Record<string,unknown>;probes?:Record<string,OneBotProbe>;directory?:{friends:OneBotDirectoryCollection;groups:OneBotDirectoryCollection};config?:{websocketClients?:WsClient[];websocketServers?:WsServer[]}};traffic?:ProtocolTraffic;freshness?:TrafficFreshness};
const titleCase=(value:string)=>value.charAt(0).toUpperCase()+value.slice(1).replaceAll('-',' ');
const eventTime=(value:string,locale:string)=>new Date(value).toLocaleTimeString(locale,{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false});
function TrafficPanel({traffic,freshness,requestFailed}:{traffic?:ProtocolTraffic;freshness?:TrafficFreshness;requestFailed:boolean}){
  const{t,locale}=useI18n();
  const[now,setNow]=useState(Date.now());
  const receivedAt=useRef(Date.now());
  useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[]);
  useEffect(()=>{receivedAt.current=Date.now()},[freshness?.checkedAt]);
  if(!traffic)return <Card><h2>{t('traffic.title')}</h2><p className="muted">{t('traffic.waiting')}</p></Card>;
  const displayStatus=trafficDisplayStatus({trafficStatus:traffic.status,freshness,requestFailed,receivedAt:receivedAt.current,now});
  const maxBucket=Math.max(1,...traffic.buckets.map(bucket=>bucket.total));
  const connectionRows=traffic.recentConnections.map(event=>[eventTime(event.at,locale),event.transport==='websocket-client'?t('traffic.wsClient'):t('traffic.wsServer'),<Badge good={event.status==='connected'||event.status==='listening'}>{event.status==='reconnecting'?t('traffic.retrying'):titleCase(event.status)}</Badge>]);
  const messageRows=traffic.recent.map(event=>[eventTime(event.at,locale),event.direction==='inbound'?t('traffic.in'):t('traffic.out'),titleCase(event.scope),`${event.bytes} B`]);
  const statusLabel=displayStatus==='live'?t('traffic.live'):displayStatus==='partial'?t('traffic.partial'):displayStatus==='stale'?t('traffic.staleStatus'):t('traffic.unavailable');
  return <>
    <Card className="traffic-card"><div className="card-section-heading"><div><h2>{t('traffic.title')}</h2><p className="muted">{t('traffic.hint')}</p></div><Badge good={displayStatus==='live'}>{statusLabel}</Badge></div>
      {requestFailed?<div className="alert error" role="status">{t('traffic.pollFailed')}</div>:displayStatus==='stale'?<div className="alert warning" role="status">{t('traffic.stale')}</div>:null}
      {traffic.error?<div className={`alert ${traffic.status==='partial'?'warning':'error'}`} role="status">{traffic.error}</div>:null}
      <div className="traffic-summary"><div><small>{t('traffic.currentRate')}</small><strong>{t('traffic.messagesPerMin',{count:traffic.oneMinute.total})}</strong><span>{t('traffic.inboundOutbound',{inbound:traffic.oneMinute.inbound,outbound:traffic.oneMinute.outbound})}</span></div><div><small>{t('traffic.rollingWindow')}</small><strong>{t('traffic.messagesPer5Min',{count:traffic.fiveMinutes.total})}</strong><span>{t('traffic.bytesObserved',{bytes:traffic.fiveMinutes.bytes})}</span></div></div>
      <div className="traffic-chart" role="img" aria-label={t('traffic.chartAria')}>{traffic.buckets.map(bucket=><div className="traffic-bucket" key={bucket.startedAt} title={t('traffic.messagesTitle',{count:bucket.total})}><div className="traffic-bars"><span className="traffic-bar inbound" style={{height:`${Math.max(bucket.inbound?6:0,bucket.inbound/maxBucket*100)}%`}}/><span className="traffic-bar outbound" style={{height:`${Math.max(bucket.outbound?6:0,bucket.outbound/maxBucket*100)}%`}}/></div><small>{new Date(bucket.startedAt).toLocaleTimeString(locale,{minute:'2-digit',second:'2-digit'})}</small></div>)}</div>
      <div className="traffic-legend"><span><i className="inbound"/>{t('traffic.inbound')}</span><span><i className="outbound"/>{t('traffic.outbound')}</span><small>{t('traffic.sampled',{time:new Date(traffic.observedAt).toLocaleTimeString(locale)})}</small></div>
    </Card>
    <Card><div className="card-section-heading"><div><h2>{t('traffic.connectionEvents')}</h2><p className="muted">{t('traffic.connectionHint')}</p></div></div>{connectionRows.length?<div className="traffic-event-table"><Table headers={[t('traffic.colTime'),t('traffic.colTransport'),t('traffic.colState')]} rows={connectionRows}/></div>:<Empty name={t('traffic.emptyConnections')}/>}</Card>
    <Card><div className="card-section-heading"><div><h2>{t('traffic.recentMessages')}</h2><p className="muted">{t('traffic.recentHint')}</p></div></div>{messageRows.length?<div className="traffic-event-table"><Table headers={[t('traffic.colTime'),t('traffic.colFlow'),t('traffic.colScope'),t('traffic.colSize')]} rows={messageRows}/></div>:<Empty name={t('traffic.emptyMessages')}/>}<p className="traffic-privacy muted">{t('traffic.privacy')}</p></Card>
  </>;
}
export function EndpointDetail({session,id}:{session:Session;id:string}){
  const{t,locale}=useI18n();
  const q=useApi<Endpoint>(`/endpoints/${id}`,endpointPollInterval);
  const canOperate=session.permissions.includes('endpoint:start');
  const napcat=useApi<NapCatStatus>(`/endpoints/${id}/napcat/status`,3000,canOperate&&q.data?.providerId==='napcat');
  const [clients,setClients]=useState<WsClient[]>([]);
  const [servers,setServers]=useState<WsServer[]>([]);
  const [wsDirty,setWsDirty]=useState(false);
  const wsDirtyRef=useRef(false);
  const [logs,setLogs]=useState<string>();
  const [busy,setBusy]=useState('');
  const [error,setError]=useState<unknown>();
  const [directory,setDirectory]=useState<'friends'|'groups'>('friends');
  const ep=q.data;
  const qq=napcat.data?.qq;
  const onebot=napcat.data?.onebot;
  const traffic=napcat.data?.traffic;
  const loggedIn=qq?.online===true||onebot?.status?.online===true;
  const qr=useApi<{qrcode:string}>(canOperate&&ep?.providerId==='napcat'&&!loggedIn?`/endpoints/${id}/napcat/login-qrcode`:'/disabled',5000);

  useEffect(()=>{
    const config=napcat.data?.onebot?.config;
    if(config&&!wsDirtyRef.current){
      setClients(config.websocketClients??[]);
      setServers(config.websocketServers??[]);
    }
  },[napcat.data?.onebot?.config,wsDirty]);

  async function wait(op:Operation,message:string){
    for(let i=0;i<30;i++){
      await new Promise(resolve=>setTimeout(resolve,500));
      const current=await api.get<Operation>(`/operations/${op.id}`);
      if(['failed','stale'].includes(current.status))throw new Error(message);
      if(current.status==='succeeded')return current;
    }
    throw new Error(`${message}: timed out`);
  }
  async function run(name:string,fn:()=>Promise<void>){
    setBusy(name);setError(undefined);
    try{await fn()}catch(cause){setError(cause)}finally{setBusy('')}
  }
  async function saveWs(){
    await run('ws',async()=>{
      const clean=<T extends {tokenConfigured?:boolean}>(value:T)=>{const next={...value};delete next.tokenConfigured;return next};
      const op=await api.mutate<Operation>(`/endpoints/${id}/napcat/onebot/websockets`,{websocketClients:clients.map(clean),websocketServers:servers.map(clean)},'PUT');
      await wait(op,'WebSocket configuration failed');
      await Promise.all([napcat.refresh(),q.refresh()]);
      wsDirtyRef.current=false;
      setWsDirty(false);
    });
  }

  if(q.loading)return <Loading/>;
  if(q.error)return <Failure error={q.error}/>;
  const endpoint=q.data!;
  const markClients=(value:WsClient[])=>{wsDirtyRef.current=true;setWsDirty(true);setClients(value)};
  const markServers=(value:WsServer[])=>{wsDirtyRef.current=true;setWsDirty(true);setServers(value)};
  const discardWs=()=>{wsDirtyRef.current=false;setWsDirty(false)};
  const deleteAvailability=actionAvailability('delete',{permissions:session.permissions,capabilities:session.capabilities,activeOperationId:endpoint.activeOperationId});
  async function deleteCurrentEndpoint(){
    setBusy('delete');
    try{
      const operation=await api.mutate<Operation>(`/endpoints/${endpoint.id}`,{expectedGeneration:endpoint.generation},'DELETE');
      await wait(operation,'Endpoint deletion failed');
      dispatchEvent(new Event(ENDPOINTS_CHANGED));
      navigate('/endpoints');
    }finally{setBusy('')}
  }

  const settings=<EndpointSettings endpoint={endpoint} refresh={q.refresh} canDelete={deleteAvailability.visible} deleteDisabled={deleteAvailability.disabled||Boolean(busy)} deleting={busy==='delete'} onDelete={deleteCurrentEndpoint}/>;
  const refreshStatus=async()=>{await Promise.all([q.refresh(),...(canOperate&&endpoint.providerId==='napcat'?[napcat.refresh()]:[])])};
  const lifecycleActions=<div className="endpoint-lifecycle-actions" aria-label={t('endpoint.lifecycle')}><Button className="endpoint-refresh-action" variant="outline" aria-label={t('endpoint.refreshStatus')} disabled={q.refreshing||napcat.refreshing||Boolean(busy)} onClick={()=>void refreshStatus()}><RefreshCw className={q.refreshing||napcat.refreshing?'refresh-spin':undefined}/><span className="refresh-label">{q.refreshing||napcat.refreshing?t('common.refreshing'):t('common.refresh')}</span></Button>{['start','stop','restart'].map(action=>{const availability=actionAvailability(action,{permissions:session.permissions,capabilities:session.capabilities,activeOperationId:endpoint.activeOperationId});return availability.visible&&<Button key={action} variant={action==='start'?'default':'outline'} busy={busy===`lifecycle-${action}`} disabled={availability.disabled||Boolean(busy)} onClick={()=>run(`lifecycle-${action}`,async()=>{const operation=await api.mutate<Operation>(`/endpoints/${endpoint.id}/operations`,{action,expectedGeneration:endpoint.generation});navigate(`/operations/${operation.id}`)})}>{action==='start'?t('endpoint.start'):action==='stop'?t('endpoint.stop'):t('endpoint.restart')}</Button>})}</div>;
  const probeCatalog=[
    ['get_status',t('endpoint.probeRuntime')],
    ['get_login_info',t('endpoint.probeIdentity')],
    ['get_version_info',t('endpoint.probeMetadata')],
    ['get_friend_list',t('endpoint.probeDirectory')],
    ['get_group_list',t('endpoint.probeDirectory')],
  ] as const;
  const directoryData=onebot?.directory;
  const currentDirectory=directoryData?.[directory];
  const probeRows=probeCatalog.map(([action,category])=>{const probe=onebot?.probes?.[action];return [<code>{action}</code>,category,probe?<Badge good={probe.ok}>{probe.ok?t('endpoint.probeAvailable'):t('endpoint.probeFailed')}</Badge>:<Badge>{t('endpoint.notObserved')}</Badge>,probe?`${probe.durationMs} ms${probe.error?` · ${probe.error}`:''}`:'—']});
  const hasTabbedConsole=canOperate&&endpoint.providerId==='napcat';

  return <Stack className={`endpoint-console${hasTabbedConsole?' endpoint-console-with-tabs':''}`}>
    <PageHeading className="endpoint-heading" kicker={t('endpoint.kicker')} title={endpoint.name} description={t('endpoint.hostedBy',{node:endpoint.node?.name??t('endpoint.unassignedNode'),id:endpoint.id})} action={lifecycleActions}/>
    <div className="health-strip">{statusLayers(endpoint.status).map(layer=><Info key={layer.label} label={t(layer.id as MessageKey)}><Badge good={['connected','online','ready','available','converged'].includes(layer.value)}>{layer.value}</Badge></Info>)}</div>
    {endpoint.activeOperation?<OperationProgressView operation={endpoint.activeOperation}/>:null}
    {hasTabbedConsole?<Tabs defaultValue="overview" className="endpoint-tabs">
      <TabsList className="endpoint-tabs-list product-tabs-list">
        <TabsTrigger className="product-tabs-trigger after:hidden" value="overview">{t('endpoint.tabOverview')}</TabsTrigger>
        <TabsTrigger className="product-tabs-trigger after:hidden" value="traffic">{t('endpoint.tabTraffic')}</TabsTrigger>
        <TabsTrigger className="product-tabs-trigger after:hidden" value="connections" disabled={!loggedIn}>{t('endpoint.tabConnections')}</TabsTrigger>
        <TabsTrigger className="product-tabs-trigger after:hidden" value="qq-data" disabled={!loggedIn}>{t('endpoint.tabQqData')}</TabsTrigger>
        <TabsTrigger className="product-tabs-trigger after:hidden" value="onebot" disabled={!loggedIn}>{t('endpoint.tabOnebot')}</TabsTrigger>
        <TabsTrigger className="product-tabs-trigger after:hidden" value="logs">{t('endpoint.tabLogs')}</TabsTrigger>
        <TabsTrigger className="product-tabs-trigger after:hidden" value="settings">{t('endpoint.tabSettings')}</TabsTrigger>
      </TabsList>
      <TabsContent value="overview" className="endpoint-tab-panel">
        <Card className="qq-account-card"><div className="card-section-heading"><div><h2>{t('endpoint.qqAccount')}</h2><p className="muted">{t('endpoint.qqAccountHint')}</p></div>{loggedIn&&<Badge good>{t('endpoint.loggedIn')}</Badge>}</div>{loggedIn?<div className="info-grid"><Info label={t('endpoint.nickname')}>{String(qq?.nickname??qq?.nick??onebot?.loginInfo?.nickname??t('endpoint.qqAccountFallback'))}</Info><Info label={t('endpoint.qqNumber')}>{String(qq?.uin??qq?.uid??onebot?.loginInfo?.user_id??'—')}</Info></div>:<div className="qq-login-panel"><div className="endpoint-qr">{qr.data?.qrcode?<QRCodeSVG value={qr.data.qrcode} size={184} role="img" aria-label={t('endpoint.qrAria')}/>:<span>{t('endpoint.waitingQr')}</span>}</div><div className="qq-login-copy"><h3>{t('endpoint.scanTitle')}</h3><p className="muted">{t('endpoint.scanBody')}</p><Button busy={busy==='qr'} disabled={Boolean(endpoint.activeOperationId)} onClick={()=>run('qr',async()=>{await wait(await api.mutate<Operation>(`/endpoints/${id}/napcat/login-qrcode`),t('operation.qrFailed'));await Promise.all([qr.refresh(),napcat.refresh(),q.refresh()])})}>{t('endpoint.refreshQr')}</Button></div></div>}</Card>
      </TabsContent>
      <TabsContent value="traffic" className="endpoint-tab-panel"><TrafficPanel traffic={traffic} freshness={napcat.data?.freshness} requestFailed={Boolean(napcat.error)}/></TabsContent>
      <TabsContent value="qq-data" className="endpoint-tab-panel">
        <Card><div className="card-section-heading"><div><h2>{t('endpoint.qqData')}</h2><p className="muted">{t('endpoint.qqDataHint')}</p></div>{currentDirectory?.observedAt?<small className="muted">{t('endpoint.observed',{time:new Date(currentDirectory.observedAt).toLocaleString(locale)})}</small>:null}</div><Tabs value={directory} onValueChange={value=>setDirectory(value as 'friends'|'groups')}><TabsList className="product-tabs-list"><TabsTrigger className="product-tabs-trigger after:hidden" value="friends">{t('endpoint.friends',{count:directoryData?.friends.count??0})}</TabsTrigger><TabsTrigger className="product-tabs-trigger after:hidden" value="groups">{t('endpoint.groups',{count:directoryData?.groups.count??0})}</TabsTrigger></TabsList>{currentDirectory&&!currentDirectory.probe.ok?<div className="alert error" role="status">{t('endpoint.refreshFailed')}{currentDirectory.observedAt?t('endpoint.refreshFailedCached'):''}. {currentDirectory.probe.error}</div>:null}{currentDirectory?.truncated?<p className="muted">{t('endpoint.showingFirst',{shown:currentDirectory.items.length,total:currentDirectory.count})}</p>:null}<TabsContent value="friends">{directoryData?.friends.items.length?<DirectoryTable key="friends" headers={[t('endpoint.colNickname'),t('endpoint.colRemark'),t('endpoint.colQq')]} items={directoryData.friends.items} total={directoryData.friends.count} truncated={directoryData.friends.truncated} row={friend=>[String(friend.nickname??'—'),String(friend.remark??'—'),String(friend.user_id)]}/>:<Empty name={t('endpoint.emptyFriends')}/>}</TabsContent><TabsContent value="groups">{directoryData?.groups.items.length?<DirectoryTable key="groups" headers={[t('endpoint.colGroup'),t('endpoint.colMembers'),t('endpoint.colId')]} items={directoryData.groups.items} total={directoryData.groups.count} truncated={directoryData.groups.truncated} row={group=>[String(group.group_name??'—'),String(group.member_count??'—'),String(group.group_id)]}/>:<Empty name={t('endpoint.emptyGroups')}/>}</TabsContent></Tabs></Card>
      </TabsContent>
      <TabsContent value="onebot" className="endpoint-tab-panel">
        <Card className="protocol-runtime"><div><h2>{t('endpoint.onebotTitle')}</h2><p>{t('endpoint.onebotBody')}</p></div><div className="runtime-facts"><Info label={t('endpoint.implementation')}>{String(onebot?.version?.app_name??'NapCat')}</Info><Info label={t('endpoint.implementationVersion')}>{String(onebot?.version?.app_version??t('endpoint.awaitingReport'))}</Info></div></Card>
        <Card><div className="card-section-heading"><div><h2>{t('endpoint.actionSupport')}</h2><p className="muted">{t('endpoint.actionSupportHint')}</p></div></div><Table headers={[t('endpoint.colAction'),t('endpoint.colLayer'),t('endpoint.colAvailability'),t('endpoint.colLatestProbe')]} rows={probeRows}/></Card>
      </TabsContent>
      <TabsContent value="connections" className="endpoint-tab-panel">
        <Card className="ws-transport-card"><PageHeading kicker={t('endpoint.wsKicker')} title={t('endpoint.wsTitle')} description={t('endpoint.wsDescription')}/><fieldset className="ws-editor-fieldset" disabled={busy==='ws'}><WebSocketConnectionEditor clients={clients} servers={servers} onClientsChange={markClients} onServersChange={markServers}/></fieldset><footer className="ws-save-bar"><p>{wsDirty?t('endpoint.wsDirty'):t('endpoint.wsClean')}</p><div className="ws-save-actions"><Button variant="outline" disabled={!wsDirty||busy==='ws'} onClick={discardWs}>{t('common.discardChanges')}</Button><Button busy={busy==='ws'} disabled={Boolean(endpoint.activeOperationId)||!wsDirty} onClick={saveWs}>{t('common.saveChanges')}</Button></div></footer></Card>
      </TabsContent>
      <TabsContent value="logs" className="endpoint-tab-panel"><Card><h2>{t('endpoint.logsTitle')}</h2><p className="muted">{t('endpoint.logsHint')}</p><Button busy={busy==='logs'} disabled={Boolean(endpoint.activeOperationId)} onClick={()=>run('logs',async()=>{const current=await wait(await api.mutate<Operation>(`/endpoints/${id}/napcat/container-logs`,{tail:250,sinceSeconds:900}),t('operation.logsFailed'));setLogs((current.result as {metadata?:{logs?:{text?:string}}})?.metadata?.logs?.text??t('endpoint.noLogs'))})}>{t('endpoint.loadLogs')}</Button>{logs!==undefined&&<pre>{logs}</pre>}</Card></TabsContent>
      <TabsContent value="settings" className="endpoint-tab-panel">{settings}</TabsContent>
    </Tabs>:settings}
    {error?<Failure error={error}/>:null}
  </Stack>;
}

function EndpointSettings({endpoint,refresh,canDelete,deleteDisabled,deleting,onDelete}:{endpoint:Endpoint;refresh:()=>Promise<void>;canDelete:boolean;deleteDisabled:boolean;deleting:boolean;onDelete:()=>Promise<void>}){const{t}=useI18n();const[name,setName]=useState(endpoint.name),[busy,setBusy]=useState(false),[confirmDelete,setConfirmDelete]=useState(false),[deleteConfirmation,setDeleteConfirmation]=useState(''),[deleteError,setDeleteError]=useState<unknown>();const closeDelete=()=>{if(deleting)return;setConfirmDelete(false);setDeleteConfirmation('');setDeleteError(undefined)};const remove=async()=>{setDeleteError(undefined);try{await onDelete()}catch(value){setDeleteError(value)}};return <Stack><Card><h2>{t('endpoint.settings')}</h2><form className="inline-form" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await api.mutate(`/endpoints/${endpoint.id}`,{name},'PATCH');await refresh();dispatchEvent(new Event(ENDPOINTS_CHANGED))}finally{setBusy(false)}}}><Input label={t('endpoints.colName')} value={name} onChange={e=>setName(e.currentTarget.value)}/><Button type="submit" busy={busy}>{t('common.rename')}</Button></form></Card>{canDelete?<Card className="danger-zone"><h2>{t('endpoint.danger')}</h2><p className="muted">{t('endpoint.dangerHint')}</p><Button variant="destructive" disabled={deleteDisabled} onClick={()=>{setDeleteConfirmation('');setDeleteError(undefined);setConfirmDelete(true)}}>{t('endpoint.delete')}</Button><Modal open={confirmDelete} onClose={closeDelete} title={t('endpoint.delete')} description={t('endpoint.deleteDescription')} footer={<><Button variant="outline" disabled={deleting} onClick={closeDelete}>{t('common.cancel')}</Button><Button variant="destructive" disabled={deleteConfirmation!==endpoint.name} busy={deleting} onClick={()=>void remove()}>{t('endpoint.delete')}</Button></>}><p>{t('endpoint.deleteBody',{name:endpoint.name})}</p><Input label={t('endpoint.confirmName')} value={deleteConfirmation} onChange={event=>setDeleteConfirmation(event.currentTarget.value)}/>{deleteError?<Failure error={deleteError} focus title={t('endpoint.deleteFailedTitle')}/>:null}</Modal></Card>:null}</Stack>}

export function Nodes({session}:{session:Session}){const{t}=useI18n();const q=useApi<Page<Node>>('/nodes');const[secret,setSecret]=useState<string>(),[error,setError]=useState<unknown>();return <Stack><PageHeading kicker={t('nodes.kicker')} title={t('nodes.title')} description={t('nodes.description')} action={session.permissions.includes('node:create')?<Button onClick={async()=>{try{setSecret((await api.requestSecret<{token:string}>('/nodes/enrollment-tokens',{name:'agent',ttlSeconds:900,labels:{}})).token)}catch(e){setError(e)}}}>{t('nodes.generateToken')}</Button>:undefined}/><State q={q}>{d=>d.items.length?<Table headers={[t('nodes.colName'),t('nodes.colProvider'),t('nodes.colHeartbeat')]} rows={d.items.map(n=>[<Link to={`/nodes/${n.id}`}>{n.name}</Link>,n.provider,<Badge good={nodeConnectionStatus(n)==='online'}>{nodeConnectionStatus(n)}</Badge>])}/>:<Empty name={t('nodes.empty')}/>}</State>{error?<Failure error={error}/>:null}<Modal open={Boolean(secret)} title={t('nodes.tokenTitle')} description={t('nodes.tokenDescription')} onClose={()=>setSecret(undefined)} footer={<Button onClick={()=>setSecret(undefined)}>{t('common.done')}</Button>}><code className="enrollment-token">{secret}</code></Modal></Stack>}
export function NodeDetail({id}:{id:string}){const{t}=useI18n();const q=useApi<Node>(`/nodes/${id}`);return <Stack><PageHeading kicker={t('nodes.detailKicker')} title={t('nodes.detailTitle')}/><State q={q}>{n=><Card><h2>{n.name}</h2><div className="info-grid"><Info label={t('nodes.runtimeDriver')}>{n.provider}</Info><Info label={t('nodes.agentConfigured')}>{n.configured?t('common.yes'):t('common.no')}</Info><Info label={t('nodes.lastHeartbeat')}>{n.lastHeartbeatAt??t('common.never')}</Info><Info label={t('nodes.lastSeen')}>{n.lastSeenAt??t('common.never')}</Info></div></Card>}</State></Stack>}
export function Providers(){const{t}=useI18n();const q=useApi<Page<Provider>>('/providers');return <Stack><PageHeading kicker={t('providers.kicker')} title={t('providers.title')}/><State q={q}>{d=>d.items.length?<Table headers={[t('providers.colProvider'),t('providers.colCapabilities'),t('providers.colAvailability')]} rows={d.items.map(p=>[p.id,p.capabilities.join(', '),<Badge good={p.availability.enabled}>{p.availability.enabled?t('providers.enabled'):p.availability.reason??t('providers.disabled')}</Badge>])}/>:<Empty name={t('providers.empty')}/>}</State></Stack>}
const activityLabel=(value:string)=>value.split(/[._-]/).map(part=>part?part[0]!.toUpperCase()+part.slice(1):part).join(' ');
export function ActivityLog({initialTab='changes'}:{initialTab?:'changes'|'audit'}){const{t}=useI18n();const operations=useApi<Page<Operation>>('/operations',operationListPollInterval),audit=useApi<Page<AuditEvent>>('/audit');return <Stack><PageHeading kicker={t('activity.kicker')} title={t('activity.title')} description={t('activity.description')}/><Tabs defaultValue={initialTab} className="activity-tabs"><TabsList className="product-tabs-list"><TabsTrigger className="product-tabs-trigger after:hidden" value="changes">{t('activity.changes')} <span className="activity-count">{operations.data?.total??'—'}</span></TabsTrigger><TabsTrigger className="product-tabs-trigger after:hidden" value="audit">{t('activity.auditLog')} <span className="activity-count">{audit.data?.total??'—'}</span></TabsTrigger></TabsList><TabsContent value="changes" className="activity-panel"><div className="section-copy"><h2>{t('activity.desiredChanges')}</h2><p>{t('activity.desiredHint')}</p></div><State q={operations}>{data=>data.items.length?<Table headers={[t('activity.colAction'),t('activity.colEndpoint'),t('activity.colStatus'),t('activity.colRequested')]} rows={data.items.map(operation=>[<Link to={`/operations/${operation.id}`}>{activityLabel(operation.action)}</Link>,<Link to={`/endpoints/${operation.endpointId}`}>{operation.endpointId}</Link>,<Badge good={operation.status==='succeeded'}>{activityLabel(operation.status)}</Badge>,operation.createdAt?new Date(operation.createdAt).toLocaleString():'—'])}/>:<Empty name={t('activity.emptyChanges')}/>}</State></TabsContent><TabsContent value="audit" className="activity-panel"><div className="section-copy"><h2>{t('activity.auditLog')}</h2><p>{t('activity.auditHint')}</p></div><State q={audit}>{data=>data.items.length?<Table headers={[t('activity.colEvent'),t('activity.colResource'),t('activity.colActor'),t('activity.colRecorded')]} rows={data.items.map(event=>[activityLabel(event.action),event.resource_type?`${activityLabel(event.resource_type)}${event.resource_id?` · ${event.resource_id}`:''}`:'—',event.actorEmail??t('activity.system'),event.created_at?new Date(event.created_at).toLocaleString():'—'])}/>:<Empty name={t('activity.emptyAudit')}/>}</State></TabsContent></Tabs></Stack>}
export function OperationDetail({id}:{id:string}){const{t}=useI18n();const q=useApi<Operation>(`/operations/${id}`,data=>data&&['queued','running'].includes(data.status)?1000:undefined);return <Stack><PageHeading kicker={t('operation.detailKicker')} title={t('operation.detailTitle')} description={t('operation.detailDescription')}/><State q={q}>{o=><><OperationProgressView operation={o}/><Card><div className="info-grid"><Info label={t('operation.action')}>{o.action}</Info><Info label={t('operation.status')}><Badge good={o.status==='succeeded'}>{o.status}</Badge></Info><Info label={t('operation.endpoint')}><Link to={`/endpoints/${o.endpointId}`}>{o.endpointId}</Link></Info><Info label={t('operation.generation')}>{o.generation}</Info><Info label={t('operation.currentStage')}>{o.progress.phase.replaceAll('-',' ')}</Info><Info label={t('operation.lastProgress')}>{new Date(o.progress.updatedAt).toLocaleString()}</Info></div></Card>{o.result!==undefined&&<Card><h2>{t('operation.result')}</h2><pre>{JSON.stringify(o.result,null,2)}</pre></Card>}</>}</State></Stack>}
function WorkspaceNav({session}:{session:Session}){const{t}=useI18n();return <nav aria-label={t('workspace.sections')} className="workspace-tabs-list product-tabs-list">{([[t('workspace.members'),'/workspace/members','member:read'],[t('workspace.alerts'),'/workspace/settings','settings:read']] as const).filter(x=>session.permissions.includes(x[2])).map(x=>{const active=location.pathname===x[1]||(location.pathname==='/workspace'&&x[1]==='/workspace/members');return <Link className="product-tabs-trigger" data-state={active?'active':'inactive'} aria-current={active?'page':undefined} key={x[1]} to={x[1]}>{x[0]}</Link>})}</nav>}
type MemberRole='admin'|'operator'|'viewer';
const roleOptions:MemberRole[]=['admin','operator','viewer'];
export function Members({session}:{session:Session}){
 const{t}=useI18n();
 const q=useApi<Page<Member>>('/workspaces/current/members'),canManage=session.permissions.includes('member:manage');
 const[adding,setAdding]=useState(false),[editing,setEditing]=useState<Member>(),[deleting,setDeleting]=useState<Member>(),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[role,setRole]=useState<MemberRole>('viewer'),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>();
 const close=()=>{setAdding(false);setEditing(undefined);setDeleting(undefined);setEmail('');setPassword('');setRole('viewer');setError(undefined)};
 const beginEdit=(member:Member)=>{setEditing(member);setEmail(member.email);setRole(member.role==='owner'?'admin':member.role);setError(undefined)};
 async function submit(event:React.FormEvent){event.preventDefault();setBusy(true);setError(undefined);try{if(adding)await api.mutate('/workspaces/current/members',{email,password,role});else if(editing)await api.mutate(`/workspaces/current/members/${editing.id}`,{email,...(editing.id===session.user.id||editing.role==='owner'?{}:{role})},'PATCH');await q.refresh();close()}catch(value){setError(value)}finally{setBusy(false)}}
 async function remove(){if(!deleting)return;setBusy(true);setError(undefined);try{await api.mutate(`/workspaces/current/members/${deleting.id}`,undefined,'DELETE');await q.refresh();close()}catch(value){setError(value)}finally{setBusy(false)}}const errorId='member-form-error';
 return <Stack><WorkspaceNav session={session}/><PageHeading title={t('members.title')} description={t('members.description')} action={canManage?<Button onClick={()=>setAdding(true)}>{t('members.add')}</Button>:undefined}/><State q={q}>{data=>data.items.length?<Table headers={[t('members.colEmail'),t('members.colRole'),t('members.colJoined'),t('members.colActions')]} rows={data.items.map(member=>[member.email,<Badge>{member.role}</Badge>,member.created_at?new Date(member.created_at).toLocaleDateString():'—',canManage&&!(member.role==='owner'&&member.id!==session.user.id)?<div className="member-actions"><Button variant="outline" size="sm" onClick={()=>beginEdit(member)}>{t('common.edit')}</Button>{member.role!=='owner'&&member.id!==session.user.id?<Button variant="outline" size="sm" onClick={()=>{setDeleting(member);setError(undefined)}}>{t('common.delete')}</Button>:null}</div>:'—'])}/>:<Empty name={t('members.empty')}/>}</State>
  <Modal open={adding||Boolean(editing)} title={adding?t('members.add'):t('members.edit')} description={adding?t('members.addHint'):t('members.editHint')} onClose={()=>!busy&&close()} footer={<><Button type="button" variant="outline" disabled={busy} onClick={close}>{t('common.cancel')}</Button><Button type="submit" form="member-form" busy={busy}>{adding?t('members.add'):t('common.saveChanges')}</Button></>}><form id="member-form" className="stack" onSubmit={submit} aria-busy={busy} aria-describedby={error?errorId:undefined}><Input label={t('members.email')} type="email" autoComplete="off" required aria-invalid={Boolean(error)} aria-describedby={error?errorId:undefined} value={email} onChange={event=>setEmail(event.currentTarget.value)}/>{adding?<Input label={t('members.initialPassword')} type="password" autoComplete="new-password" minLength={12} required description={t('members.passwordHint')} aria-invalid={Boolean(error)} aria-describedby={error?errorId:undefined} value={password} onChange={event=>setPassword(event.currentTarget.value)}/>:null}<Select label={t('members.role')} value={role} disabled={editing?.id===session.user.id||editing?.role==='owner'} aria-invalid={Boolean(error)} aria-describedby={error?errorId:undefined} onChange={event=>setRole(event.currentTarget.value as MemberRole)}>{roleOptions.map(value=><option key={value} value={value}>{value}</option>)}</Select>{error?<Failure id={errorId} error={error} focus title={t('members.saveFailed')}/>:null}</form></Modal>
  <Modal open={Boolean(deleting)} title={t('members.deleteTitle')} description={t('members.deleteHint')} onClose={()=>!busy&&close()} footer={<><Button variant="outline" disabled={busy} onClick={close}>{t('common.cancel')}</Button><Button variant="destructive" busy={busy} onClick={remove}>{t('members.deleteTitle')}</Button></>}><p>{t('members.deleteBody',{email:deleting?.email??''})}</p>{error?<Failure id="member-delete-error" error={error} focus title={t('members.deleteFailed')}/>:null}</Modal>
 </Stack>
}
export function Account({session}:{session:Session}){const{t}=useI18n();const[currentPassword,setCurrentPassword]=useState(''),[newPassword,setNewPassword]=useState(''),[confirmation,setConfirmation]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>(),[saved,setSaved]=useState(false),errorId='password-form-error';async function submit(event:React.FormEvent){event.preventDefault();setSaved(false);setError(undefined);if(newPassword!==confirmation){setError(new Error(t('account.mismatch')));return}setBusy(true);try{await api.mutate('/auth/password',{currentPassword,newPassword},'PUT');setCurrentPassword('');setNewPassword('');setConfirmation('');setSaved(true)}catch(value){setError(value)}finally{setBusy(false)}}return <Stack><PageHeading kicker={t('account.kicker')} title={t('account.title')} description={t('account.description')}/><Card><div className="info-grid"><Info label={t('account.email')}>{session.user.email}</Info><Info label={t('account.workspaceRole')}>{session.role}</Info></div><form className="account-password-form" onSubmit={submit} aria-busy={busy} aria-describedby={error?errorId:undefined}><Input label={t('account.currentPassword')} type="password" autoComplete="current-password" required aria-invalid={Boolean(error)} aria-describedby={error?errorId:undefined} value={currentPassword} onChange={event=>setCurrentPassword(event.currentTarget.value)}/><Input label={t('account.newPassword')} type="password" autoComplete="new-password" minLength={12} required description={t('account.passwordHint')} aria-invalid={Boolean(error)} aria-describedby={error?errorId:undefined} value={newPassword} onChange={event=>setNewPassword(event.currentTarget.value)}/><Input label={t('account.confirmPassword')} type="password" autoComplete="new-password" minLength={12} required aria-invalid={Boolean(error)} aria-describedby={error?errorId:undefined} value={confirmation} onChange={event=>setConfirmation(event.currentTarget.value)}/>{error?<Failure id={errorId} error={error} focus title={t('account.changeFailed')}/>:null}{saved?<p className="success-message" role="status" aria-live="polite">{t('account.saved')}</p>:null}<Button type="submit" busy={busy}>{t('account.change')}</Button></form></Card></Stack>}
function TargetPicker({label,description,targets,selected,disabled,onChange}:{label:string;description:string;targets:NotificationTarget[];selected:string[];disabled:boolean;onChange:(ids:string[])=>void}){const{t}=useI18n();return <fieldset className="alert-target-picker" disabled={disabled}><legend>{label}</legend><p>{description}</p>{targets.length?<div className="alert-target-options">{targets.map(target=><label key={target.id}><input type="checkbox" checked={selected.includes(target.id)} onChange={event=>onChange(event.currentTarget.checked?[...selected,target.id]:selected.filter(id=>id!==target.id))}/><span><strong>{target.name}</strong><small>{target.email}</small></span></label>)}</div>:<p className="muted">{t('alerts.addTargetFirst')}</p>}</fieldset>}
export function Settings({session}:{session:Session}){
 const{t}=useI18n();
 const q=useApi<AlertSettings>('/workspaces/current/settings/alerts'),[form,setForm]=useState<AlertSettings>(),[targetName,setTargetName]=useState(''),[targetEmail,setTargetEmail]=useState(''),[busy,setBusy]=useState(''),[error,setError]=useState<unknown>(),[saved,setSaved]=useState(false),can=session.permissions.includes('settings:manage');
 useEffect(()=>{if(q.data)setForm(structuredClone(q.data))},[q.data]);
 if(q.loading||!form)return <Loading/>;if(q.error)return <Failure error={q.error}/>;
 const updateDefault=(key:'offlineTargetIds'|'recoveryTargetIds',ids:string[])=>setForm({...form,defaults:{...form.defaults,[key]:ids}});
 const updateEndpoint=(endpointId:string,key:'offlineTargetIds'|'recoveryTargetIds',ids:string[])=>setForm({...form,endpoints:form.endpoints.map(endpoint=>endpoint.id===endpointId?{...endpoint,[key]:ids}:endpoint)});
 async function addTarget(event:React.FormEvent){event.preventDefault();setBusy('target');setError(undefined);try{await api.mutate('/workspaces/current/notification-targets',{name:targetName,email:targetEmail});setTargetName('');setTargetEmail('');await q.refresh()}catch(value){setError(value)}finally{setBusy('')}}
 async function removeTarget(targetId:string){setBusy(`delete-${targetId}`);setError(undefined);try{await api.mutate(`/workspaces/current/notification-targets/${targetId}`,undefined,'DELETE');await q.refresh()}catch(value){setError(value)}finally{setBusy('')}}
 const save=async()=>{setBusy('save');setSaved(false);setError(undefined);try{await api.mutate('/workspaces/current/settings/alerts',{graceSeconds:form.graceSeconds,offlineTargetIds:form.defaults.offlineTargetIds,recoveryTargetIds:form.defaults.recoveryTargetIds,endpoints:form.endpoints.map(endpoint=>({endpointId:endpoint.id,offlineTargetIds:endpoint.offlineTargetIds,recoveryTargetIds:endpoint.recoveryTargetIds}))},'PUT');await q.refresh();setSaved(true)}catch(value){setError(value)}finally{setBusy('')}};
 return <Stack><WorkspaceNav session={session}/><PageHeading title={t('alerts.title')} description={t('alerts.description')}/>
  <Card className="alert-settings-card"><div className="card-section-heading"><div><h2>{t('alerts.targets')}</h2><p className="muted">{t('alerts.targetsHint')}</p></div></div>{form.targets.length?<div className="notification-target-list">{form.targets.map(target=><div key={target.id}><div><strong>{target.name}</strong><small>{target.email}</small></div>{can?<Button variant="outline" size="sm" busy={busy===`delete-${target.id}`} disabled={Boolean(busy)&&busy!==`delete-${target.id}`} onClick={()=>void removeTarget(target.id)}>{t('common.remove')}</Button>:null}</div>)}</div>:<div className="ws-empty">{t('alerts.noTargets')}</div>}{can?<form className="notification-target-form" onSubmit={addTarget}><Input label={t('alerts.targetName')} required value={targetName} onChange={event=>setTargetName(event.currentTarget.value)}/><Input label={t('alerts.emailAddress')} type="email" required value={targetEmail} onChange={event=>setTargetEmail(event.currentTarget.value)}/><Button type="submit" busy={busy==='target'} disabled={Boolean(busy)&&busy!=='target'}>{t('alerts.addTarget')}</Button></form>:null}</Card>
  <Card className="alert-settings-card"><div className="card-section-heading"><div><h2>{t('alerts.defaults')}</h2><p className="muted">{t('alerts.defaultsHint')}</p></div></div><Input label={t('alerts.grace')} type="number" min={30} max={86400} disabled={!can} value={form.graceSeconds} onChange={event=>setForm({...form,graceSeconds:Number(event.currentTarget.value)})}/><div className="alert-picker-grid"><TargetPicker label={t('alerts.offline')} description={t('alerts.offlineDefaultHint')} targets={form.targets} selected={form.defaults.offlineTargetIds} disabled={!can} onChange={ids=>updateDefault('offlineTargetIds',ids)}/><TargetPicker label={t('alerts.recovered')} description={t('alerts.recoveredDefaultHint')} targets={form.targets} selected={form.defaults.recoveryTargetIds} disabled={!can} onChange={ids=>updateDefault('recoveryTargetIds',ids)}/></div></Card>
  <Card className="alert-settings-card"><div className="card-section-heading"><div><h2>{t('alerts.subscriptions')}</h2><p className="muted">{t('alerts.subscriptionsHint')}</p></div></div>{form.endpoints.length?<div className="endpoint-alert-list">{form.endpoints.map(endpoint=><section key={endpoint.id} className="endpoint-alert-card"><header><div><h3>{endpoint.name}</h3><p>{endpoint.providerId} · {endpoint.id}</p></div><Badge>{t('alerts.subscriptionCount',{count:endpoint.offlineTargetIds.length+endpoint.recoveryTargetIds.length})}</Badge></header><div className="alert-picker-grid"><TargetPicker label={t('alerts.offline')} description={t('alerts.offlineEndpointHint')} targets={form.targets} selected={endpoint.offlineTargetIds} disabled={!can} onChange={ids=>updateEndpoint(endpoint.id,'offlineTargetIds',ids)}/><TargetPicker label={t('alerts.recovered')} description={t('alerts.recoveredEndpointHint')} targets={form.targets} selected={endpoint.recoveryTargetIds} disabled={!can} onChange={ids=>updateEndpoint(endpoint.id,'recoveryTargetIds',ids)}/></div></section>)}</div>:<div className="ws-empty">{t('alerts.noEndpoints')}</div>}</Card>
  {error?<Failure error={error} focus title={t('alerts.saveFailed')}/>:null}{saved?<p className="success-message" role="status">{t('alerts.saved')}</p>:null}{can?<div className="alert-save-bar"><p>{t('alerts.saveHint')}</p><Button busy={busy==='save'} disabled={Boolean(busy)&&busy!=='save'} onClick={()=>void save()}>{t('alerts.save')}</Button></div>:null}
 </Stack>
}
