import {Alert,Badge,Button,Checkbox,Group,Modal,NumberInput,Select,Stack,Table,Text,TextInput,Title} from '@mantine/core';
import {useEffect,useMemo,useState} from 'react';
import {Link,useNavigate,useParams} from 'react-router-dom';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import type {ColumnDef} from '@tanstack/react-table';
import {QRCodeSVG} from 'qrcode.react';
import {api} from './api';
import {DataTable} from './data-table';
import {SchemaForm} from './schema-form';
import {Empty,Failure,Loading} from './states';
import {actionAvailability,nodeConnectionStatus,statusLayers} from './policy';
import type {Credential,Endpoint,Node,Operation,Page,Provider,ResendSettings,SchemaField,Session} from './types';

const query=<T,>(key:string,path:string)=>useQuery({queryKey:[key],queryFn:()=>api.get<T>(path),retry:false});
const state=<T,>(q:{isLoading:boolean;error:Error|null;data:T|undefined},render:(data:T)=>React.ReactNode)=>q.isLoading?<Loading/>:q.error?<Failure error={q.error}/>:render(q.data!);

export function Overview(){const q=query<{endpoints:number;operations:number}>('overview','/workspaces/current/summary');return <Stack><Title order={2}>Operational overview</Title>{state(q,data=><Group><Alert title="Endpoints">{data.endpoints}</Alert><Alert title="Operations">{data.operations}</Alert></Group>)}</Stack>}

export function Endpoints({session}:{session:Session}){
  const q=query<Page<Endpoint>>('endpoints','/endpoints');
  const nodes=query<Page<Node>>('nodes-for-endpoint','/nodes');
  const [provider,setProvider]=useState<string>();
  const [nodeId,setNodeId]=useState<string|null>(null);
  const navigate=useNavigate();
  const create=useMutation({mutationFn:(values:Record<string,unknown>)=>api.mutate<Endpoint>('/endpoints',{providerId:provider,nodeId,...values}),onSuccess:endpoint=>navigate(`/endpoints/${endpoint.id}`)});
  const columns=useMemo<ColumnDef<Endpoint>[]>(()=>[
    {header:'Name',accessorKey:'name',cell:info=><Link to={`/endpoints/${info.row.original.id}`}>{String(info.getValue())}</Link>},
    {header:'Provider',accessorKey:'providerId'},
    {id:'assigned-node',header:'Node',cell:info=>info.row.original.node?.name??'Unassigned'},
    ...statusLayers({node:'',runtime:'',provider:'',protocol:'',convergence:''}).map(layer=>({id:`status-${layer.label.toLowerCase()}`,header:layer.label,cell:({row}:{row:{original:Endpoint}})=><Badge variant="light">{statusLayers(row.original.status).find(item=>item.label===layer.label)?.value}</Badge>})),
  ],[]);
  if(q.isLoading||nodes.isLoading)return <Loading/>;if(q.error||nodes.error)return <Failure error={q.error??nodes.error}/>;
  const fields:SchemaField[]=[{key:'name',label:'Name',type:'string',required:true},...(provider?session.capabilities.configurationSchemas?.[provider]??[]:[])];
  const canCreate=actionAvailability('create',{permissions:session.permissions,capabilities:session.capabilities,activeOperationId:null}).visible;
  return <Stack><Group justify="space-between"><Title order={2}>Endpoints</Title>{canCreate&&<Button onClick={()=>setProvider('')}>Create endpoint</Button>}</Group>{q.data!.items.length===0?<Empty name="endpoints"/>:<DataTable data={q.data!.items} columns={columns}/>}<Modal opened={provider!==undefined} onClose={()=>{setProvider(undefined);setNodeId(null)}} title={provider?'Configure endpoint':'Create endpoint'}>
    {!provider?<Stack>{Object.entries(session.capabilities.providers??{}).map(([id,gate])=><div key={id}><Button fullWidth disabled={!gate.enabled} onClick={()=>gate.enabled&&setProvider(id)}>{id==='napcat'?'NapCat':id==='fake'?'Fake':id}</Button>{gate.reason&&<Text size="sm" c="dimmed">{gate.reason}</Text>}</div>)}</Stack>:<Stack><Select label="Node" required data={nodes.data!.items.map(node=>({value:node.id,label:node.name}))} value={nodeId} onChange={setNodeId}/><SchemaForm fields={fields} submitLabel="Create" busy={create.isPending} onSubmit={values=>nodeId&&create.mutate(values)}/></Stack>}{create.error&&<Failure error={create.error}/>}
  </Modal></Stack>;
}

export function EndpointDetail({session}:{session:Session}){
  const {id}=useParams();const nav=useNavigate();const client=useQueryClient();
  const canOperate=session.permissions.includes('endpoint:start');
  const q=query<Endpoint>(`endpoint-${id}`,`/endpoints/${id}`);
  const qr=useQuery({queryKey:[`endpoint-${id}-napcat-qr`],queryFn:()=>api.get<{qrcode:string}>(`/endpoints/${id}/napcat/login-qrcode`),enabled:canOperate&&q.data?.providerId==='napcat',retry:false,refetchInterval:5000});
  const napcat=useQuery({queryKey:[`endpoint-${id}-napcat-status`],queryFn:()=>api.get<{qq:null|{uin?:string;nickname?:string};onebot:null|{status?:{online?:boolean};loginInfo?:Record<string,unknown>}}>(`/endpoints/${id}/napcat/status`),enabled:canOperate&&q.data?.providerId==='napcat',retry:false,refetchInterval:3000});
  const refreshQr=useMutation({mutationFn:()=>api.mutate<Operation>(`/endpoints/${id}/napcat/login-qrcode`),onSuccess:async operation=>{for(let attempt=0;attempt<20;attempt++){await new Promise(resolve=>setTimeout(resolve,500));const current=await api.get<Operation>(`/operations/${operation.id}`);if(current.status==='failed'||current.status==='stale')throw new Error('QR refresh failed');if(current.status==='succeeded'){await Promise.all([qr.refetch(),napcat.refetch(),q.refetch()]);return}}throw new Error('QR refresh timed out')}});
  const [containerLogs,setContainerLogs]=useState<string>();
  const loadLogs=useMutation({mutationFn:()=>api.mutate<Operation>(`/endpoints/${id}/napcat/container-logs`,{tail:250,sinceSeconds:900}),onSuccess:async operation=>{for(let attempt=0;attempt<20;attempt++){await new Promise(resolve=>setTimeout(resolve,500));const current=await api.get<Operation>(`/operations/${operation.id}`);if(current.status==='failed'||current.status==='stale')throw new Error('Container log request failed');if(current.status==='succeeded'){const logs=(current.result as {metadata?:{logs?:{text?:string}}}|undefined)?.metadata?.logs?.text;setContainerLogs(logs??'No container logs returned.');return}}throw new Error('Container log request timed out')}});
  const op=useMutation({mutationFn:(action:string)=>api.mutate<Operation>(`/endpoints/${id}/operations`,{action,expectedGeneration:q.data!.generation}),onSuccess:value=>nav(`/operations/${value.id}`)});
  const save=useMutation({mutationFn:(name:string)=>api.mutate<Endpoint>(`/endpoints/${id}`,{name},'PATCH'),onSuccess:()=>client.invalidateQueries({queryKey:[`endpoint-${id}`]})});
  if(q.isLoading)return <Loading/>;if(q.error)return <Failure error={q.error}/>;const ep=q.data!;
  return <Stack><Title order={2}>{ep.name}</Title><Text>Node: {ep.node?.name??'Unassigned'}</Text><Group>{statusLayers(ep.status).map(layer=><Badge key={layer.label}>{layer.label}: {layer.value}</Badge>)}</Group>{canOperate&&ep.providerId==='napcat'&&<Stack gap="sm"><Title order={3}>NapCat login</Title>{qr.data?.qrcode?<QRCodeSVG value={qr.data.qrcode} size={180} role="img" aria-label="NapCat QR code"/>:<Text c="dimmed">NapCat WebUI is connected, but the QQ login kernel has not published a QR code yet.</Text>}<Group><Button onClick={()=>refreshQr.mutate()} loading={refreshQr.isPending} disabled={Boolean(ep.activeOperationId)}>Refresh QR code</Button><Badge>{napcat.data?.qq?.uin??'QQ pending'}</Badge><Badge color={napcat.data?.onebot?.status?.online?'green':'gray'}>OneBot {napcat.data?.onebot?.status?.online?'online':'offline'}</Badge></Group>{napcat.data?.qq?.nickname&&<Text>{napcat.data.qq.nickname}</Text>}{refreshQr.error&&<Failure error={refreshQr.error}/>}<Title order={3}>NapCat container logs</Title><Group><Button variant="light" onClick={()=>loadLogs.mutate()} loading={loadLogs.isPending} disabled={Boolean(ep.activeOperationId)}>Load container logs</Button><Text size="sm" c="dimmed">Last 250 lines from the past 15 minutes; credentials are redacted.</Text></Group>{containerLogs!==undefined&&<pre style={{maxHeight:360,overflow:'auto',whiteSpace:'pre-wrap',background:'var(--mantine-color-dark-8)',color:'var(--mantine-color-gray-1)',padding:12,borderRadius:6}}>{containerLogs}</pre>}{loadLogs.error&&<Failure error={loadLogs.error}/>}</Stack>}{ep.activeOperationId&&<Alert color="yellow" title="Operation in progress">Conflicting actions are disabled until <Link to={`/operations/${ep.activeOperationId}`}>{ep.activeOperationId}</Link> completes.</Alert>}<Title order={3}>Endpoint details</Title><form onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);save.mutate(String(form.get('name')??''))}}><Group align="end"><TextInput name="name" label="Name" required defaultValue={ep.name}/><Button type="submit" loading={save.isPending}>Rename</Button></Group></form><Title order={3}>Operations</Title><Group>{['start','stop','restart'].map(kind=>{const availability=actionAvailability(kind,{permissions:session.permissions,capabilities:session.capabilities,activeOperationId:ep.activeOperationId??null},ep.providerId);return availability.visible?<Button key={kind} disabled={availability.disabled} onClick={()=>op.mutate(kind)}>{kind[0]!.toUpperCase()+kind.slice(1)}</Button>:null})}</Group>{(op.error||save.error)&&<Failure error={op.error??save.error}/>}</Stack>;
}

export function Nodes({session}:{session:Session}){const q=query<Page<Node>>('nodes','/nodes');const [secret,setSecret]=useState<string>();const token=useMutation({mutationFn:()=>api.requestSecret<{token:string}>('/nodes/enrollment-tokens',{name:'agent',ttlSeconds:900,labels:{}}),onSuccess:value=>setSecret(value.token)});if(q.isLoading)return <Loading/>;if(q.error)return <Failure error={q.error}/>;const canManage=session.permissions.includes('node:create');return <Stack><Group justify="space-between"><Title order={2}>Nodes</Title>{canManage&&<Button onClick={()=>token.mutate()}>Generate enrollment token</Button>}</Group>{q.data!.items.length===0?<Empty name="nodes"/>:<Table><Table.Thead><Table.Tr><Table.Th>Name</Table.Th><Table.Th>Provider</Table.Th><Table.Th>Heartbeat</Table.Th></Table.Tr></Table.Thead><Table.Tbody>{q.data!.items.map(node=><Table.Tr key={node.id}><Table.Td><Link to={`/nodes/${node.id}`}>{node.name}</Link></Table.Td><Table.Td>{node.provider}</Table.Td><Table.Td><Badge>{nodeConnectionStatus(node)}</Badge></Table.Td></Table.Tr>)}</Table.Tbody></Table>}{token.error&&<Failure error={token.error}/>}<Modal opened={Boolean(secret)} onClose={()=>setSecret(undefined)} title="One-time enrollment token" closeButtonProps={{'aria-label':'Dismiss token'}}><Text ff="monospace">{secret}</Text><Text c="dimmed">Copy it now. It will not be shown again.</Text><Button mt="md" onClick={()=>setSecret(undefined)}>Close</Button></Modal></Stack>}

export function Providers(){const q=query<Page<Provider>>('providers','/providers');return <Stack><Title order={2}>Providers</Title>{state(q,data=>data.items.length?<Table><Table.Thead><Table.Tr><Table.Th>Provider</Table.Th><Table.Th>Capabilities</Table.Th><Table.Th>Availability</Table.Th></Table.Tr></Table.Thead><Table.Tbody>{data.items.map(p=><Table.Tr key={p.id}><Table.Td>{p.id}</Table.Td><Table.Td>{p.capabilities.join(', ')}</Table.Td><Table.Td><Badge color={p.availability.enabled?'green':'gray'}>{p.availability.enabled?'enabled':p.availability.reason??'disabled'}</Badge></Table.Td></Table.Tr>)}</Table.Tbody></Table>:<Empty name="providers"/>)}</Stack>}
export function Operations(){const q=query<Page<Operation>>('operations','/operations');const columns=useMemo<ColumnDef<Operation>[]>(()=>[{header:'Operation',accessorKey:'action',cell:info=><Link to={`/operations/${info.row.original.id}`}>{String(info.getValue()??info.row.original.id)}</Link>},{header:'Endpoint',accessorKey:'endpointId'},{header:'State',accessorKey:'status',cell:info=><Badge>{String(info.getValue())}</Badge>},{header:'Created',accessorKey:'createdAt'}],[]);return <Stack><Title order={2}>Operations</Title>{state(q,data=>data.items.length?<DataTable data={data.items} columns={columns}/>:<Empty name="operations"/>)}</Stack>}
function JsonCollection({title,path}:{title:string;path:string}){const q=query<Page<Record<string,unknown>>>(title,path);return <Stack><Title order={2}>{title}</Title>{state(q,data=>data.items.length?<Table><Table.Tbody>{data.items.map((item,index)=><Table.Tr key={String(item.id??index)}><Table.Td>{String(item.action??item.name??item.email??item.id)}</Table.Td><Table.Td>{String(item.role??item.resource_type??item.createdAt??item.created_at??'')}</Table.Td></Table.Tr>)}</Table.Tbody></Table>:<Empty name={title}/>)}</Stack>}
export const Audit=()=> <JsonCollection title="Audit events" path="/audit"/>;
function WorkspaceSubnav({session}:{session:Session}){const links=[['Members','/workspace/members','member:read'],['Credentials','/workspace/credentials','credential:read'],['Settings','/workspace/settings','settings:read']];return <Group>{links.filter(([, ,permission])=>session.permissions.includes(permission!)).map(([label,to])=><Button key={to} component={Link} to={to!} variant="subtle">{label}</Button>)}</Group>}
export const Members=({session}:{session:Session})=> <Stack><WorkspaceSubnav session={session}/><JsonCollection title="Workspace members" path="/workspaces/current/members"/></Stack>;
export function Credentials({session}:{session:Session}){const q=query<Page<Credential>>('credentials','/workspaces/current/credentials');const client=useQueryClient();const [name,setName]=useState('');const [value,setValue]=useState('');const create=useMutation({mutationFn:()=>api.mutate('/workspaces/current/credentials',{name,value}),onSuccess:()=>{setName('');setValue('');void client.invalidateQueries({queryKey:['credentials']})}});const canManage=session.permissions.includes('credential:manage');return <Stack><WorkspaceSubnav session={session}/><Title order={2}>Credentials</Title>{state(q,data=>data.items.length?<Table><Table.Tbody>{data.items.map(item=><Table.Tr key={item.id}><Table.Td>{item.name}</Table.Td><Table.Td>{item.configured?'Configured':'Missing'}</Table.Td></Table.Tr>)}</Table.Tbody></Table>:<Empty name="credentials"/>)}{canManage&&<form onSubmit={event=>{event.preventDefault();create.mutate()}}><Group align="end"><TextInput label="Name" required value={name} onChange={event=>setName(event.currentTarget.value)}/><TextInput label="Secret value" type="password" required value={value} onChange={event=>setValue(event.currentTarget.value)}/><Button type="submit" loading={create.isPending}>Add credential</Button></Group></form>}{create.error&&<Failure error={create.error}/>}</Stack>}
export function Settings({session}:{session:Session}){const q=query<ResendSettings>('resend-settings','/workspaces/current/settings/resend');const client=useQueryClient();const [form,setForm]=useState<{enabled:boolean;recipient:string;from:string;graceSeconds:number;apiKey:string}|null>(null);useEffect(()=>{if(q.data&&!form)setForm({...q.data,apiKey:''})},[q.data,form]);const save=useMutation({mutationFn:()=>{if(!form)throw new Error('Settings are not loaded');const {apiKey,...settings}=form;return api.mutate<ResendSettings>('/workspaces/current/settings/resend',apiKey?{...settings,apiKey}:settings,'PUT')},onSuccess:value=>{setForm({...value,apiKey:''});client.setQueryData(['resend-settings'],value)}});const test=useMutation({mutationFn:()=>api.mutate('/workspaces/current/settings/resend/test')});if(q.isLoading||!form)return <Loading/>;if(q.error)return <Failure error={q.error}/>;const canManage=session.permissions.includes('settings:manage');return <Stack><WorkspaceSubnav session={session}/><Title order={2}>Email alerts</Title><Text c="dimmed">Email workspace admins when a NapCat node stays offline, then when it recovers.</Text><Checkbox label="Enable alerts" checked={form.enabled} disabled={!canManage} onChange={event=>setForm({...form,enabled:event.currentTarget.checked})}/><TextInput label="Recipient" type="email" required disabled={!canManage} value={form.recipient} onChange={event=>setForm({...form,recipient:event.currentTarget.value})}/><TextInput label="From" required disabled={!canManage} value={form.from} onChange={event=>setForm({...form,from:event.currentTarget.value})}/><NumberInput label="Offline grace (seconds)" min={30} max={86400} required disabled={!canManage} value={form.graceSeconds} onChange={value=>setForm({...form,graceSeconds:Number(value)})}/><TextInput label="Resend API key" type="password" placeholder={q.data!.apiKeyConfigured?'Leave blank to keep current key':'re_…'} disabled={!canManage} value={form.apiKey} onChange={event=>setForm({...form,apiKey:event.currentTarget.value})}/>{q.data!.apiKeyConfigured&&<Badge color="green">API key configured</Badge>}<Group>{canManage&&<Button onClick={()=>save.mutate()} loading={save.isPending}>Save</Button>}<Button variant="light" disabled={!canManage||!q.data!.apiKeyConfigured} onClick={()=>test.mutate()} loading={test.isPending}>Send test email</Button></Group>{test.isSuccess&&<Alert color="green">Test email queued.</Alert>}{(save.error||test.error)&&<Failure error={save.error??test.error}/>}</Stack>}
export function OperationDetail(){const {id}=useParams();const client=useQueryClient();const q=useQuery({queryKey:[`operation-${id}`],queryFn:()=>api.get<Operation>(`/operations/${id}`),retry:false,refetchInterval:query=>{const data=query.state.data as Operation|undefined;return data&&['queued','running'].includes(data.status)?2000:false}});useEffect(()=>{const data=q.data;if(data&&['succeeded','failed','stale'].includes(data.status)){void api.get<Endpoint>(`/endpoints/${data.endpointId}`).then(endpoint=>client.setQueryData([`endpoint-${data.endpointId}`],endpoint));void api.get<Page<Endpoint>>('/endpoints').then(page=>client.setQueryData(['endpoints'],page));}},[client,q.data]);return <Stack><Title order={2}>Operation detail</Title>{state(q,data=><pre>{JSON.stringify(data,null,2)}</pre>)}</Stack>}
export function NodeDetail(){const {id}=useParams();const q=query<Node>(`node-${id}`,`/nodes/${id}`);return <Stack><Title order={2}>Node detail</Title>{state(q,data=><pre>{JSON.stringify(data,null,2)}</pre>)}</Stack>}
