import{expect,test,type Page}from'@playwright/test';

const endpoint={id:'11111111-1111-4111-8111-111111111111',name:'Primary QQ bot',providerId:'napcat',node:null,generation:0,desired:{state:'stopped'},status:{node:'unassigned',runtime:'unknown',provider:'unknown',protocol:'unknown',convergence:'reconciling'},activeOperationId:null};
const session={user:{id:'owner-id',email:'owner@example.com',name:'Owner'},workspace:{id:'workspace-id',name:'Primary'},role:'owner',permissions:['workspace:read','endpoint:read','operation:read','audit:read','member:read','settings:read','settings:manage'],capabilities:{operations:[],providers:{}}};

async function mockAlerts(page:Page){
 const targets:Array<{id:string;name:string;email:string}>=[];let saved:unknown;
 const settings=()=>({graceSeconds:180,targets,defaults:{offlineTargetIds:[],recoveryTargetIds:[]},endpoints:[{id:endpoint.id,name:endpoint.name,providerId:endpoint.providerId,offlineTargetIds:[],recoveryTargetIds:[]}]});
 await page.route('**/api/v1/**',async route=>{const request=route.request(),path=new URL(request.url()).pathname.replace('/api/v1',''),method=request.method(),json=(body:unknown,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)});
  if(path==='/auth/session')return json(session);if(path==='/auth/csrf')return json({csrfToken:'csrf'});if(path==='/endpoints')return json({items:[endpoint],page:1,pageSize:25,total:1});if(path==='/workspaces/current/settings/alerts'&&method==='GET')return json(settings());
  if(path==='/workspaces/current/notification-targets'&&method==='POST'){const body=request.postDataJSON() as{name:string;email:string},target={id:'22222222-2222-4222-8222-222222222222',...body};targets.push(target);return json(target,201)}
  if(path==='/workspaces/current/settings/alerts'&&method==='PUT'){saved=request.postDataJSON();return json(settings())}
  return json({items:[],page:1,pageSize:25,total:0});
 });
 return{saved:()=>saved};
}

test('admin configures multi-target defaults and per-endpoint alert subscriptions',async({page},testInfo)=>{const state=await mockAlerts(page);await page.setViewportSize({width:1180,height:900});await page.goto('/workspace/settings');await expect(page.getByRole('heading',{name:'Alert subscriptions'})).toBeVisible();await expect(page.getByLabel('Resend API key')).toHaveCount(0);await expect(page.getByLabel('From')).toHaveCount(0);await page.getByLabel('Target name').fill('Primary on-call');await page.getByLabel('Email address').fill('alerts@example.com');await page.getByRole('button',{name:'Add target'}).click();const deliveryTargets=page.getByRole('heading',{name:'Delivery targets'}).locator('..').locator('..').locator('..');await expect(deliveryTargets.getByText('alerts@example.com',{exact:true})).toBeVisible();const defaults=page.getByRole('heading',{name:'Defaults for new endpoints'}).locator('..').locator('..').locator('..');await defaults.getByRole('group',{name:'Endpoint offline'}).getByLabel(/Primary on-call/).check();await defaults.getByRole('group',{name:'Endpoint recovered'}).getByLabel(/Primary on-call/).check();const endpointCard=page.locator('.endpoint-alert-card',{hasText:'Primary QQ bot'});await endpointCard.getByRole('group',{name:'Endpoint offline'}).getByLabel(/Primary on-call/).check();await page.getByRole('button',{name:'Save subscriptions'}).click();await expect(page.getByRole('status')).toHaveText('Alert subscriptions saved.');expect(state.saved()).toMatchObject({graceSeconds:180,offlineTargetIds:['22222222-2222-4222-8222-222222222222'],recoveryTargetIds:['22222222-2222-4222-8222-222222222222'],endpoints:[{endpointId:endpoint.id,offlineTargetIds:['22222222-2222-4222-8222-222222222222'],recoveryTargetIds:[]}]});await page.screenshot({path:testInfo.outputPath('alert-subscriptions.png'),fullPage:true})});
