import { describe, expect, it } from "vitest";
import { readFile } from "node:fs/promises";
import { encryptSecret, decryptSecret, redactCredential, digest, migrationSql, InMemoryDatabase, PostgresDatabase, runMigration, runtimeRequestForProvider } from "../src/index.js";
describe("database security and durable mutation",()=>{
it("uses the recommended default NapCat CPU and memory limits",()=>expect(runtimeRequestForProvider("napcat").resources).toEqual({cpuMillis:1000,memoryMiB:1024}));
it("defines all tenant tables and database invariants",()=>{for(const table of ["users","sessions","workspaces","members","nodes","enrollment_tokens","endpoints","operations","observations","credentials","audit_events","outbox_events"]) expect(migrationSql).toContain(`CREATE TABLE IF NOT EXISTS ${table}`); expect(migrationSql).toContain("workspace_id"); expect(migrationSql).toContain("CREATE EXTENSION IF NOT EXISTS pgcrypto"); expect(migrationSql).toContain("CREATE TABLE IF NOT EXISTS"); expect(migrationSql).toContain("UNIQUE (workspace_id, endpoint_id, idempotency_key)");});
it("includes ordered 0002 outbound-agent durability schema",()=>{for(const fragment of ["0002_outbound_agent","ADD COLUMN IF NOT EXISTS credential_hash","ADD COLUMN IF NOT EXISTS labels","CREATE TABLE IF NOT EXISTS agent_commands","lease_deadline","connection_epoch","node_id uuid NOT NULL","metadata jsonb NOT NULL DEFAULT '{}'"]) expect(migrationSql).toContain(fragment);});
it("preserves the first-published historical migration bytes",async()=>{const [one,two]=await Promise.all([readFile(new URL("../migrations/0001_control_plane.sql",import.meta.url),"utf8"),readFile(new URL("../migrations/0002_outbound_agent.sql",import.meta.url),"utf8")]);expect(digest(one)).toBe("21e94c5207ad27a74cd15a205268b97aab465f2ab162777a053e971192db08b8");expect(digest(two)).toBe("1723679204313029ac5ce9c82be735e3b6e461dc0062b1a8a7ccd6d142ec5143");expect(one).toMatch(/^BEGIN;[\s\S]*COMMIT;\n$/);expect(two).toMatch(/^BEGIN;[\s\S]*COMMIT;\n$/);});
it("treats a schema with additional newer migrations as ready for rolling replicas",async()=>{const pool={query:async(sql:string,params?:unknown[])=>{if(sql.includes("to_regclass"))return{rows:[{ledger:"schema_migrations",endpoints:"endpoints"}]};const names=(params?.[0] as string[])??[];return{rows:[...(await Promise.all(names.map(async name=>({name,checksum:digest(await readFile(new URL(`../migrations/${name}`,import.meta.url),"utf8"))})))),{name:"9999_future.sql",checksum:"future"}]}}};expect(await new PostgresDatabase(pool as never).migrationsReady()).toBe(true)});
it("rejects readiness when a required migration checksum drifts",async()=>{const pool={query:async(sql:string,params?:unknown[])=>sql.includes("to_regclass")?{rows:[{ledger:"schema_migrations",endpoints:"endpoints"}]}:{rows:((params?.[0] as string[])??[]).map(name=>({name,checksum:"wrong"}))}};expect(await new PostgresDatabase(pool as never).migrationsReady()).toBe(false)});
it("rolls back migration SQL and ledger insertion together when either fails",async()=>{const queries:string[]=[];const client={query:async(sql:string)=>{queries.push(sql);if(sql.startsWith("INSERT INTO schema_migrations"))throw new Error("ledger failure")}};await expect(runMigration(client as never,{name:"0001_test.sql",sql:"CREATE TABLE test(id int)",checksum:"abc"})).rejects.toThrow("ledger failure");expect(queries).toEqual(["BEGIN","CREATE TABLE test(id int)","INSERT INTO schema_migrations(name,checksum) VALUES($1,$2)","ROLLBACK"]);});
it("runs explicitly marked concurrent-index migrations outside a transaction and makes replay safe",async()=>{const queries:string[]=[];const client={query:async(sql:string)=>{queries.push(sql);return{rows:[],rowCount:1}}};await runMigration(client as never,{name:"0011_index.sql",sql:"-- botroost:no-transaction\nDROP INDEX CONCURRENTLY IF EXISTS test_idx;\nCREATE INDEX CONCURRENTLY test_idx ON test(id);\n",checksum:"abc"});expect(queries).toEqual(["SET lock_timeout='5s'","SET statement_timeout='30min'","DROP INDEX CONCURRENTLY IF EXISTS test_idx;","CREATE INDEX CONCURRENTLY test_idx ON test(id);","INSERT INTO schema_migrations(name,checksum) VALUES($1,$2)","RESET statement_timeout","RESET lock_timeout"]);});
it("keeps endpoint deletion schema changes bounded and builds hot-table indexes concurrently",async()=>{const [deletion,activeIndex,deletedIndex,dropLegacy,observationIndex]=await Promise.all(["0010_endpoint_deletion.sql","0011_endpoint_active_name_index.sql","0012_endpoint_deleted_at_index.sql","0013_endpoint_drop_legacy_name_constraint.sql","0016_observations_endpoint_created_index.sql"].map(name=>readFile(new URL(`../migrations/${name}`,import.meta.url),"utf8")));expect(deletion).toContain("SET LOCAL lock_timeout");expect(deletion).toContain("NOT VALID");expect(deletion).toContain("VALIDATE CONSTRAINT");for(const sql of [activeIndex,deletedIndex]){expect(sql).toMatch(/^-- botroost:no-transaction\nDROP INDEX CONCURRENTLY IF EXISTS/);expect(sql).toMatch(/CREATE (?:UNIQUE )?INDEX CONCURRENTLY/);expect(sql).not.toMatch(/BEGIN|COMMIT/)}expect(observationIndex).toMatch(/^-- botroost:no-transaction\nCREATE INDEX CONCURRENTLY IF NOT EXISTS/);expect(observationIndex).not.toContain("DROP INDEX");for(const fragment of ["ON observations(endpoint_id,created_at DESC)","indisvalid","indisready","indnkeyatts=2","pg_get_indexdef(i.indexrelid,1,true)='endpoint_id'","pg_get_indexdef(i.indexrelid,2,true)='created_at'","i.indoption[0]=0","i.indoption[1]=3","1 / count(*)"])expect(observationIndex).toContain(fragment);expect(dropLegacy).toContain("DROP CONSTRAINT IF EXISTS endpoints_workspace_id_name_key");});
it("encrypts credential envelopes and never exposes plaintext",()=>{const key=Buffer.alloc(32,7);const envelope=encryptSecret("super-secret",key);expect(JSON.stringify(envelope)).not.toContain("super-secret");expect(decryptSecret(envelope,key)).toBe("super-secret");expect(redactCredential({name:"bot",...envelope})).toEqual({name:"bot",configured:true});});
it("deletes endpoint-owned durable records transactionally before the endpoint",async()=>{const queries:string[]=[];const client={query:async(sql:string)=>{queries.push(sql);return{rows:[],rowCount:1}},release:()=>{}};const pool={connect:async()=>client} as never;await new PostgresDatabase(pool).deleteEndpoint("workspace","endpoint");expect(queries).toEqual(["BEGIN","DELETE FROM observations WHERE workspace_id=$1 AND endpoint_id=$2","DELETE FROM agent_commands WHERE workspace_id=$1 AND endpoint_id=$2","DELETE FROM outbox_events WHERE operation_id IN (SELECT id FROM operations WHERE workspace_id=$1 AND endpoint_id=$2)","DELETE FROM operations WHERE workspace_id=$1 AND endpoint_id=$2","DELETE FROM endpoints WHERE workspace_id=$1 AND id=$2","COMMIT"]);});
it("atomically creates desired operation audit and outbox with idempotency and CAS",()=>{const db=new InMemoryDatabase();const ws=db.createWorkspace("a");const ep=db.createEndpoint(ws.id,"e");const first=db.mutateEndpoint({workspaceId:ws.id,endpointId:ep.id,action:"start",expectedGeneration:0,idempotencyKey:"k"});expect(first.replayed).toBe(false);expect(db.operations).toHaveLength(1);expect(db.audits).toHaveLength(1);expect(db.outbox).toHaveLength(1);expect(db.endpoints[0]!.generation).toBe(1);expect(db.mutateEndpoint({workspaceId:ws.id,endpointId:ep.id,action:"start",expectedGeneration:0,idempotencyKey:"k"}).operation.id).toBe(first.operation.id);expect(()=>db.mutateEndpoint({workspaceId:ws.id,endpointId:ep.id,action:"stop",expectedGeneration:0,idempotencyKey:"x"})).toThrow("generation conflict");expect(()=>db.mutateEndpoint({workspaceId:"other",endpointId:ep.id,action:"start",expectedGeneration:1,idempotencyKey:"idor"})).toThrow("not found");});});
