import { describe, expect, it } from "vitest";
import { encryptSecret, decryptSecret, redactCredential, migrationSql, InMemoryDatabase, runMigration } from "../src/index.js";
describe("database security and durable mutation",()=>{
it("defines all tenant tables and database invariants",()=>{for(const table of ["users","sessions","workspaces","members","nodes","enrollment_tokens","endpoints","operations","observations","credentials","audit_events","outbox_events"]) expect(migrationSql).toContain(`CREATE TABLE IF NOT EXISTS ${table}`); expect(migrationSql).toContain("workspace_id"); expect(migrationSql).toContain("CREATE EXTENSION IF NOT EXISTS pgcrypto"); expect(migrationSql).toContain("CREATE TABLE IF NOT EXISTS"); expect(migrationSql).toContain("UNIQUE (workspace_id, endpoint_id, idempotency_key)");});
it("includes ordered 0002 outbound-agent durability schema",()=>{for(const fragment of ["0002_outbound_agent","ADD COLUMN IF NOT EXISTS credential_hash","ADD COLUMN IF NOT EXISTS labels","CREATE TABLE IF NOT EXISTS agent_commands","lease_deadline","connection_epoch","node_id uuid NOT NULL","metadata jsonb NOT NULL DEFAULT '{}'"]) expect(migrationSql).toContain(fragment);});
it("leaves transaction ownership to the migration runner",()=>{expect(migrationSql).not.toMatch(/^BEGIN;|^COMMIT;|\nBEGIN;|\nCOMMIT;/m);});
it("rolls back migration SQL and ledger insertion together when either fails",async()=>{const queries:string[]=[];const client={query:async(sql:string)=>{queries.push(sql);if(sql.startsWith("INSERT INTO schema_migrations"))throw new Error("ledger failure")}};await expect(runMigration(client as never,{name:"0001_test.sql",sql:"CREATE TABLE test(id int)",checksum:"abc"})).rejects.toThrow("ledger failure");expect(queries).toEqual(["BEGIN","CREATE TABLE test(id int)","INSERT INTO schema_migrations(name,checksum) VALUES($1,$2)","ROLLBACK"]);});
it("encrypts credential envelopes and never exposes plaintext",()=>{const key=Buffer.alloc(32,7);const envelope=encryptSecret("super-secret",key);expect(JSON.stringify(envelope)).not.toContain("super-secret");expect(decryptSecret(envelope,key)).toBe("super-secret");expect(redactCredential({name:"bot",...envelope})).toEqual({name:"bot",configured:true});});
it("atomically creates desired operation audit and outbox with idempotency and CAS",()=>{const db=new InMemoryDatabase();const ws=db.createWorkspace("a");const ep=db.createEndpoint(ws.id,"e");const first=db.mutateEndpoint({workspaceId:ws.id,endpointId:ep.id,action:"start",expectedGeneration:0,idempotencyKey:"k"});expect(first.replayed).toBe(false);expect(db.operations).toHaveLength(1);expect(db.audits).toHaveLength(1);expect(db.outbox).toHaveLength(1);expect(db.endpoints[0]!.generation).toBe(1);expect(db.mutateEndpoint({workspaceId:ws.id,endpointId:ep.id,action:"start",expectedGeneration:0,idempotencyKey:"k"}).operation.id).toBe(first.operation.id);expect(()=>db.mutateEndpoint({workspaceId:ws.id,endpointId:ep.id,action:"stop",expectedGeneration:0,idempotencyKey:"x"})).toThrow("generation conflict");expect(()=>db.mutateEndpoint({workspaceId:"other",endpointId:ep.id,action:"start",expectedGeneration:1,idempotencyKey:"idor"})).toThrow("not found");});});
