import { createCipheriv, createDecipheriv, createHash, randomBytes, randomUUID } from "node:crypto";
import { readdir, readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import pg, { type Pool, type PoolClient } from "pg";

export type Role = "owner" | "admin" | "operator" | "viewer";
export type Action = "start" | "stop" | "restart";
export interface Envelope { algorithm: "aes-256-gcm"; iv: string; tag: string; ciphertext: string }
export interface Principal { userId: string; email: string; workspaceId: string; role: Role; sessionId: string; csrfHash: string }
export interface Endpoint { id: string; workspaceId: string; name: string; providerId: string; node: { id: string; name: string } | null; generation: number; desired: { state: "running" | "stopped" }; status: { node: string; runtime: string; provider: string; protocol: string; convergence: string } }
export interface Operation { id: string; workspaceId: string; endpointId: string; generation: number; action: Action; idempotencyKey: string; status: "queued"|"running"|"succeeded"|"failed"|"stale"; attempts: number; result: unknown; createdAt: string; updatedAt: string; claimedAt: string | null }
export interface NodeCredential { nodeId: string; workspaceId: string; nodeSecret: string }
export interface AuthenticatedNode { id: string; workspaceId: string; name: string; connectionEpoch: number }
export interface AgentCommand { commandId: string; operationId: string; workspaceId: string; nodeId: string; endpointId: string; generation: number; connectionEpoch: number; attempt: number; action: Action; runtimeRequest: unknown; metadata: Record<string, unknown> }
export class DatabaseError extends Error { constructor(public code: "not_found"|"conflict"|"idempotency_mismatch"|"already_bootstrapped"|"unauthorized", message:string=code){super(message)} }
export const digest = (value:string) => createHash("sha256").update(value).digest("hex");
export function encryptSecret(value:string,key:Buffer):Envelope { if(key.length!==32) throw new Error("master key must be 32 bytes"); const iv=randomBytes(12), c=createCipheriv("aes-256-gcm",key,iv); const ciphertext=Buffer.concat([c.update(value,"utf8"),c.final()]); return {algorithm:"aes-256-gcm",iv:iv.toString("base64"),tag:c.getAuthTag().toString("base64"),ciphertext:ciphertext.toString("base64")}; }
export function decryptSecret(e:Envelope,key:Buffer){ const d=createDecipheriv("aes-256-gcm",key,Buffer.from(e.iv,"base64"));d.setAuthTag(Buffer.from(e.tag,"base64"));return Buffer.concat([d.update(Buffer.from(e.ciphertext,"base64")),d.final()]).toString("utf8"); }
export function redactCredential(c:{name:string}&Envelope){return {name:c.name,configured:Boolean(c.ciphertext)}}
const mapEndpoint=(r:Record<string,unknown>):Endpoint=>{const desired=r.desired_state as {state:"running"|"stopped"};const observation=(r.observation_state as Record<string,unknown>|null)??null;const observedStatus=observation&&typeof observation.node==="string"?observation:null;return{id:String(r.id),workspaceId:String(r.workspace_id),name:String(r.name),providerId:String(r.provider_id),node:r.node_id?{id:String(r.node_id),name:String(r.node_name)}:null,generation:Number(r.generation),desired,status:observedStatus?{node:String(observedStatus.node),runtime:String(observedStatus.runtime),provider:String(observedStatus.provider),protocol:String(observedStatus.protocol),convergence:String(observedStatus.convergence)}:{node:r.node_id?"online":"unassigned",runtime:observation?"ready":"unknown",provider:observation?"available":"unknown",protocol:observation?"connected":"unknown",convergence:observation&&Number(r.observation_generation)===Number(r.generation)?"converged":"reconciling"}}};
const mapOperation=(r:Record<string,unknown>):Operation=>({id:String(r.id),workspaceId:String(r.workspace_id),endpointId:String(r.endpoint_id),generation:Number(r.generation),action:r.action as Action,idempotencyKey:String(r.idempotency_key),status:r.status as Operation["status"],attempts:Number(r.attempts),result:r.result??null,createdAt:new Date(String(r.created_at)).toISOString(),updatedAt:new Date(String(r.updated_at)).toISOString(),claimedAt:r.claimed_at?new Date(String(r.claimed_at)).toISOString():null});
const mapCommand=(r:Record<string,unknown>):AgentCommand=>({commandId:String(r.id),operationId:String(r.operation_id),workspaceId:String(r.workspace_id),nodeId:String(r.node_id),endpointId:String(r.endpoint_id),generation:Number(r.generation),connectionEpoch:Number(r.connection_epoch),attempt:Number(r.attempts),action:r.action as Action,runtimeRequest:r.runtime_request,metadata:(r.metadata as Record<string,unknown>)??{}});
const migrationDirectory=fileURLToPath(new URL("../migrations",import.meta.url));
async function readMigrations(){const names=(await readdir(migrationDirectory)).filter(x=>/^\d{4}_.+\.sql$/.test(x)).sort();return (await Promise.all(names.map(async name=>`-- ${name}\n${await readFile(`${migrationDirectory}/${name}`,"utf8")}`))).join("\n")}

export class PostgresDatabase {
  readonly pool: Pool;
  constructor(connection: string|Pool){this.pool=typeof connection==="string"?new pg.Pool({connectionString:connection}):connection}
  async close(){await this.pool.end()}
  async ping(){await this.pool.query("SELECT 1")}
  async migrate(){const client=await this.pool.connect();try{await client.query("SELECT pg_advisory_lock(hashtext('botroost:migrations'))");await client.query("CREATE TABLE IF NOT EXISTS schema_migrations(name text PRIMARY KEY,checksum text NOT NULL,applied_at timestamptz NOT NULL DEFAULT now())");for(const name of (await readdir(migrationDirectory)).filter(x=>/^\d{4}_.+\.sql$/.test(x)).sort()){const sql=await readFile(`${migrationDirectory}/${name}`,"utf8"),checksum=digest(sql),applied=(await client.query("SELECT checksum FROM schema_migrations WHERE name=$1",[name])).rows[0];if(applied){if(applied.checksum!==checksum)throw new Error(`migration checksum mismatch: ${name}`);continue}await client.query("BEGIN");try{await client.query(sql);await client.query("INSERT INTO schema_migrations(name,checksum) VALUES($1,$2)",[name,checksum]);await client.query("COMMIT")}catch(error){await client.query("ROLLBACK");throw error}}}finally{try{await client.query("SELECT pg_advisory_unlock(hashtext('botroost:migrations'))")}finally{client.release()}}}
  async migrationsReady(){const r=await this.pool.query("SELECT to_regclass('public.schema_migrations') ledger,to_regclass('public.endpoints') endpoints,(SELECT count(*)::int FROM schema_migrations) applied");const expected=(await readdir(migrationDirectory)).filter(x=>/^\d{4}_.+\.sql$/.test(x)).length;return Boolean(r.rows[0]?.ledger&&r.rows[0]?.endpoints&&Number(r.rows[0]?.applied)===expected)}
  private async tx<T>(fn:(c:PoolClient)=>Promise<T>){const c=await this.pool.connect();try{await c.query("BEGIN");const result=await fn(c);await c.query("COMMIT");return result}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}}
  async bootstrapOwner(input:{email:string;passwordHash:string;workspaceName:string}){return this.tx(async c=>{await c.query("LOCK TABLE users IN EXCLUSIVE MODE");const n=await c.query("SELECT count(*)::int n FROM users");if(n.rows[0].n)throw new DatabaseError("already_bootstrapped");const userId=randomUUID(),workspaceId=randomUUID();await c.query("INSERT INTO users(id,email,password_hash) VALUES($1,$2,$3)",[userId,input.email.toLowerCase(),input.passwordHash]);await c.query("INSERT INTO workspaces(id,name) VALUES($1,$2)",[workspaceId,input.workspaceName]);await c.query("INSERT INTO members(workspace_id,user_id,role) VALUES($1,$2,'owner')",[workspaceId,userId]);return{userId,workspaceId,email:input.email.toLowerCase()}})}
  async findUserByEmail(email:string){const r=await this.pool.query("SELECT id,email,password_hash FROM users WHERE email=$1",[email.toLowerCase()]);return r.rows[0] as {id:string,email:string,password_hash:string}|undefined}
  async createSession(userId:string,tokenHash:string,csrfHash:string,expiresAt:Date){const id=randomUUID();await this.pool.query("INSERT INTO sessions(id,user_id,token_hash,csrf_hash,expires_at) VALUES($1,$2,$3,$4,$5)",[id,userId,tokenHash,csrfHash,expiresAt]);return id}
  async principalForToken(tokenHash:string){const r=await this.pool.query(`SELECT s.id session_id,s.csrf_hash,u.id user_id,u.email,m.workspace_id,m.role FROM sessions s JOIN users u ON u.id=s.user_id JOIN members m ON m.user_id=u.id WHERE s.token_hash=$1 AND s.revoked_at IS NULL AND s.expires_at>now() ORDER BY m.created_at LIMIT 1`,[tokenHash]);const x=r.rows[0];return x?{sessionId:x.session_id,csrfHash:x.csrf_hash,userId:x.user_id,email:x.email,workspaceId:x.workspace_id,role:x.role as Role}:null}
  async revokeSession(tokenHash:string){await this.pool.query("UPDATE sessions SET revoked_at=now() WHERE token_hash=$1",[tokenHash])}
  async workspace(id:string){return (await this.pool.query("SELECT id,name,created_at FROM workspaces WHERE id=$1",[id])).rows[0]??null}
  async workspaceSettings(id:string){const row=(await this.pool.query("SELECT settings FROM workspaces WHERE id=$1",[id])).rows[0];if(!row)throw new DatabaseError("not_found");return row.settings as Record<string,unknown>}
  async summary(workspaceId:string){const r=await this.pool.query("SELECT (SELECT count(*)::int FROM endpoints WHERE workspace_id=$1) endpoints,(SELECT count(*)::int FROM operations WHERE workspace_id=$1) operations",[workspaceId]);return r.rows[0]}
  async members(workspaceId:string){return (await this.pool.query("SELECT u.id,u.email,m.role,m.created_at FROM members m JOIN users u ON u.id=m.user_id WHERE m.workspace_id=$1 ORDER BY m.created_at",[workspaceId])).rows}
  async credentials(workspaceId:string){return (await this.pool.query("SELECT id,name,created_at \"createdAt\",updated_at \"updatedAt\" FROM credentials WHERE workspace_id=$1 ORDER BY created_at",[workspaceId])).rows.map(row=>({...row,configured:true}))}
  async createCredential(workspaceId:string,name:string,value:string,key:Buffer){const id=randomUUID(),e=encryptSecret(value,key);const r=await this.pool.query("INSERT INTO credentials(id,workspace_id,name,algorithm,iv,tag,ciphertext) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id,name,created_at \"createdAt\",updated_at \"updatedAt\"",[id,workspaceId,name,e.algorithm,e.iv,e.tag,e.ciphertext]);return{...r.rows[0],configured:true}}
  async addMember(workspaceId:string,input:{email:string;role:Role;passwordHash:string}){return this.tx(async c=>{let u=(await c.query("SELECT id FROM users WHERE email=$1",[input.email.toLowerCase()])).rows[0];if(!u){u={id:randomUUID()};await c.query("INSERT INTO users(id,email,password_hash) VALUES($1,$2,$3)",[u.id,input.email.toLowerCase(),input.passwordHash])}await c.query("INSERT INTO members(workspace_id,user_id,role) VALUES($1,$2,$3) ON CONFLICT(workspace_id,user_id) DO UPDATE SET role=excluded.role",[workspaceId,u.id,input.role]);return{id:u.id,email:input.email.toLowerCase(),role:input.role}})}
  async nodes(workspaceId:string){return (await this.pool.query("SELECT id,name,provider,credential_id IS NOT NULL OR credential_hash IS NOT NULL configured,labels,last_heartbeat_at \"lastHeartbeatAt\",connection_epoch \"connectionEpoch\",created_at FROM nodes WHERE workspace_id=$1 AND revoked_at IS NULL ORDER BY created_at",[workspaceId])).rows}
  async node(workspaceId:string,id:string){return (await this.pool.query("SELECT id,name,provider,credential_id IS NOT NULL OR credential_hash IS NOT NULL configured,labels,last_heartbeat_at \"lastHeartbeatAt\",connection_epoch \"connectionEpoch\",revoked_at \"revokedAt\",created_at FROM nodes WHERE workspace_id=$1 AND id=$2",[workspaceId,id])).rows[0]??null}
  async createNode(workspaceId:string,input:{name:string;provider:string;credential?:string|undefined},key:Buffer){return this.tx(async c=>{let credentialId:null|string=null;if(input.credential){credentialId=randomUUID();const e=encryptSecret(input.credential,key);await c.query("INSERT INTO credentials(id,workspace_id,name,algorithm,iv,tag,ciphertext) VALUES($1,$2,$3,$4,$5,$6,$7)",[credentialId,workspaceId,`node:${input.name}`,e.algorithm,e.iv,e.tag,e.ciphertext])}const id=randomUUID();const r=await c.query("INSERT INTO nodes(id,workspace_id,name,provider,credential_id) VALUES($1,$2,$3,$4,$5) RETURNING id,name,provider,credential_id IS NOT NULL configured,created_at",[id,workspaceId,input.name,input.provider,credentialId]);return r.rows[0]})}
  async deleteNode(workspaceId:string,id:string){const r=await this.pool.query("UPDATE nodes SET revoked_at=now() WHERE id=$1 AND workspace_id=$2 AND revoked_at IS NULL",[id,workspaceId]);if(!r.rowCount)throw new DatabaseError("not_found")}
  async createEnrollment(workspaceId:string,tokenHash:string,expiresAt:Date,input:{name?:string;labels?:Record<string,string>;metadata?:Record<string,unknown>}={}){const id=randomUUID();await this.pool.query("INSERT INTO enrollment_tokens(id,workspace_id,token_hash,expires_at,name,labels,metadata) VALUES($1,$2,$3,$4,$5,$6,$7)",[id,workspaceId,tokenHash,expiresAt,input.name??"agent",input.labels??{},input.metadata??{}]);return{id,expiresAt:expiresAt.toISOString(),name:input.name??"agent",labels:input.labels??{}}}
  async enrollNode(input:{tokenHash:string;provider:string;agentVersion?:string;nodeSecretHash:string;nodeSecret:string}):Promise<NodeCredential>{return this.tx(async c=>{const token=(await c.query("SELECT * FROM enrollment_tokens WHERE token_hash=$1 FOR UPDATE",[input.tokenHash])).rows[0];if(!token||token.revoked_at||token.used_at||new Date(token.expires_at).getTime()<=Date.now())throw new DatabaseError("conflict","enrollment token is invalid");const nodeId=randomUUID();await c.query("INSERT INTO nodes(id,workspace_id,name,provider,credential_hash,enrollment_token_id,labels,agent_version) VALUES($1,$2,$3,$4,$5,$6,$7,$8)",[nodeId,token.workspace_id,token.name,input.provider,input.nodeSecretHash,token.id,token.labels,input.agentVersion??null]);await c.query("UPDATE enrollment_tokens SET used_at=now() WHERE id=$1",[token.id]);return{nodeId,workspaceId:token.workspace_id,nodeSecret:input.nodeSecret}})}
  async authenticateNode(secretHash:string):Promise<AuthenticatedNode|null>{const r=await this.pool.query("SELECT id,workspace_id,name,connection_epoch FROM nodes WHERE credential_hash=$1 AND revoked_at IS NULL",[secretHash]);const x=r.rows[0];return x?{id:x.id,workspaceId:x.workspace_id,name:x.name,connectionEpoch:Number(x.connection_epoch)}:null}
  async heartbeat(nodeId:string,input:{observedAt:string;runtimes:{endpointId:string;generation:number;runtime:string;provider:string;protocol:string;convergence:string;metadata?:Record<string,unknown>|undefined}[]}){return this.tx(async c=>{const n=(await c.query("UPDATE nodes SET last_heartbeat_at=$2,connection_epoch=connection_epoch+1,heartbeat_metadata=$3,updated_at=now() WHERE id=$1 AND revoked_at IS NULL RETURNING workspace_id,connection_epoch",[nodeId,input.observedAt,{runtimes:input.runtimes.length}])).rows[0];if(!n)throw new DatabaseError("unauthorized");for(const runtime of input.runtimes){await c.query("INSERT INTO observations(id,workspace_id,endpoint_id,generation,state) SELECT $1,workspace_id,id,$3,$4 FROM endpoints WHERE id=$2 AND node_id=$5 AND workspace_id=$6",[randomUUID(),runtime.endpointId,runtime.generation,{node:"online",runtime:runtime.runtime,provider:runtime.provider,protocol:runtime.protocol,convergence:runtime.convergence,metadata:runtime.metadata??{}},nodeId,n.workspace_id])}return{connectionEpoch:Number(n.connection_epoch)}})}
  async endpoints(workspaceId:string){return (await this.pool.query(`SELECT e.*,n.name node_name,o.state observation_state,o.generation observation_generation FROM endpoints e LEFT JOIN nodes n ON n.id=e.node_id LEFT JOIN LATERAL (SELECT state,generation FROM observations WHERE endpoint_id=e.id ORDER BY created_at DESC LIMIT 1) o ON true WHERE e.workspace_id=$1 ORDER BY e.created_at`,[workspaceId])).rows.map(mapEndpoint)}
  async endpoint(workspaceId:string,id:string){const r=await this.pool.query(`SELECT e.*,n.name node_name,o.state observation_state,o.generation observation_generation FROM endpoints e LEFT JOIN nodes n ON n.id=e.node_id LEFT JOIN LATERAL (SELECT state,generation FROM observations WHERE endpoint_id=e.id ORDER BY created_at DESC LIMIT 1) o ON true WHERE e.workspace_id=$1 AND e.id=$2`,[workspaceId,id]);return r.rows[0]?mapEndpoint(r.rows[0]):null}
  async createEndpoint(workspaceId:string,name:string,providerId:string,nodeId?:string){if(nodeId&&!(await this.node(workspaceId,nodeId)))throw new DatabaseError("not_found");const id=randomUUID();const r=await this.pool.query("INSERT INTO endpoints(id,workspace_id,node_id,name,provider_id) VALUES($1,$2,$3,$4,$5) RETURNING *,NULL::text node_name,NULL::jsonb observation_state,NULL::bigint observation_generation",[id,workspaceId,nodeId??null,name,providerId]);return mapEndpoint(r.rows[0])}
  async updateEndpoint(workspaceId:string,id:string,name:string){const r=await this.pool.query("UPDATE endpoints SET name=$3,updated_at=now() WHERE workspace_id=$1 AND id=$2 RETURNING *,NULL::text node_name,NULL::jsonb observation_state,NULL::bigint observation_generation",[workspaceId,id,name]);if(!r.rows[0])throw new DatabaseError("not_found");return mapEndpoint(r.rows[0])}
  async deleteEndpoint(workspaceId:string,id:string){const r=await this.pool.query("DELETE FROM endpoints WHERE workspace_id=$1 AND id=$2",[workspaceId,id]);if(!r.rowCount)throw new DatabaseError("not_found")}
  async mutateEndpoint(input:{workspaceId:string;endpointId:string;actorUserId:string;action:Action;expectedGeneration:number;idempotencyKey:string}){return this.tx(async c=>{const requestHash=digest(JSON.stringify({action:input.action,expectedGeneration:input.expectedGeneration}));const previous=await c.query("SELECT * FROM operations WHERE workspace_id=$1 AND endpoint_id=$2 AND idempotency_key=$3",[input.workspaceId,input.endpointId,input.idempotencyKey]);if(previous.rows[0]){if(previous.rows[0].request_hash!==requestHash)throw new DatabaseError("idempotency_mismatch");return{operation:mapOperation(previous.rows[0]),replayed:true}}const er=await c.query("SELECT * FROM endpoints WHERE workspace_id=$1 AND id=$2 FOR UPDATE",[input.workspaceId,input.endpointId]);const ep=er.rows[0];if(!ep)throw new DatabaseError("not_found");if(Number(ep.generation)!==input.expectedGeneration)throw new DatabaseError("conflict","generation conflict");const active=await c.query("SELECT 1 FROM operations WHERE endpoint_id=$1 AND status IN ('queued','running')",[ep.id]);if(active.rowCount)throw new DatabaseError("conflict","operation conflict");const generation=Number(ep.generation)+1,desired={state:input.action==="stop"?"stopped":"running"};await c.query("UPDATE endpoints SET generation=$3,desired_state=$4,updated_at=now() WHERE workspace_id=$1 AND id=$2",[input.workspaceId,input.endpointId,generation,desired]);const id=randomUUID();const op=(await c.query("INSERT INTO operations(id,workspace_id,endpoint_id,generation,action,idempotency_key,request_hash,status,desired_state) VALUES($1,$2,$3,$4,$5,$6,$7,'queued',$8) RETURNING *",[id,input.workspaceId,input.endpointId,generation,input.action,input.idempotencyKey,requestHash,desired])).rows[0];await c.query("INSERT INTO audit_events(id,workspace_id,actor_user_id,action,resource_type,resource_id,metadata) VALUES($1,$2,$3,'operation.queued','operation',$4,$5)",[randomUUID(),input.workspaceId,input.actorUserId,id,{action:input.action,generation}]);await c.query("INSERT INTO outbox_events(id,workspace_id,operation_id,event_type,payload) VALUES($1,$2,$3,'operation.queued',$4)",[randomUUID(),input.workspaceId,id,{operationId:id}]);return{operation:mapOperation(op),replayed:false}})}
  async operations(workspaceId:string){return (await this.pool.query("SELECT * FROM operations WHERE workspace_id=$1 ORDER BY created_at DESC",[workspaceId])).rows.map(mapOperation)}
  async operation(workspaceId:string,id:string){const r=await this.pool.query("SELECT * FROM operations WHERE workspace_id=$1 AND id=$2",[workspaceId,id]);return r.rows[0]?mapOperation(r.rows[0]):null}
  async audit(workspaceId:string){return (await this.pool.query("SELECT id,action,resource_type,resource_id,metadata,created_at FROM audit_events WHERE workspace_id=$1 ORDER BY created_at DESC",[workspaceId])).rows}
  async repairMissingOutbox(){const r=await this.pool.query(`INSERT INTO outbox_events(id,workspace_id,operation_id,event_type,payload) SELECT gen_random_uuid(),o.workspace_id,o.id,'operation.queued',jsonb_build_object('operationId',o.id) FROM operations o LEFT JOIN outbox_events e ON e.operation_id=o.id WHERE o.status='queued' AND e.id IS NULL ON CONFLICT(operation_id) DO NOTHING`);return r.rowCount??0}
  async processOne(){return this.tx(async c=>{const r=await c.query(`SELECT e.id event_id,o.* FROM outbox_events e JOIN operations o ON o.id=e.operation_id WHERE e.processed_at IS NULL AND e.available_at<=now() ORDER BY e.created_at FOR UPDATE OF e SKIP LOCKED LIMIT 1`);const op=r.rows[0];if(!op)return false;await c.query("UPDATE outbox_events SET claimed_at=now(),attempts=attempts+1 WHERE id=$1",[op.event_id]);const ep=(await c.query("SELECT e.*,n.connection_epoch FROM endpoints e LEFT JOIN nodes n ON n.id=e.node_id WHERE e.workspace_id=$1 AND e.id=$2 FOR UPDATE OF e",[op.workspace_id,op.endpoint_id])).rows[0];const stale=!ep||Number(ep.generation)!==Number(op.generation);if(stale){await c.query("UPDATE operations SET status='stale',result=$2,updated_at=now() WHERE id=$1",[op.id,{reason:"generation_fence"}]);await c.query("UPDATE outbox_events SET processed_at=now() WHERE id=$1",[op.event_id]);return true}if(ep.node_id){const commandId=randomUUID();const runtimeRequest={approvedArtifactId:"artifact:fake:v1",approvedEgressProfile:"egress:none",resources:{cpuMillis:100,memoryMiB:64},storage:{kind:"ephemeral",sizeMiB:16}};await c.query("INSERT INTO agent_commands(id,workspace_id,node_id,endpoint_id,operation_id,generation,connection_epoch,action,runtime_request,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(operation_id) DO NOTHING",[commandId,op.workspace_id,ep.node_id,op.endpoint_id,op.id,op.generation,ep.connection_epoch,op.action,runtimeRequest,{desiredState:op.desired_state}]);await c.query("UPDATE operations SET status='running',claimed_at=coalesce(claimed_at,now()),attempts=attempts+1,node_id=$2,connection_epoch=$3,metadata=$4,updated_at=now() WHERE id=$1 AND status='queued'",[op.id,ep.node_id,ep.connection_epoch,{dispatch:"agent",runtimeRequest}]);await c.query("UPDATE outbox_events SET processed_at=now() WHERE id=$1",[op.event_id]);return true}await c.query("UPDATE operations SET status='running',claimed_at=now(),attempts=attempts+1,updated_at=now() WHERE id=$1 AND status='queued'",[op.id]);const state={state:op.action==="stop"?"stopped":"running",provider:"fake"};await c.query("INSERT INTO observations(id,workspace_id,endpoint_id,operation_id,generation,state) VALUES($1,$2,$3,$4,$5,$6)",[randomUUID(),op.workspace_id,op.endpoint_id,op.id,op.generation,state]);await c.query("UPDATE operations SET status='succeeded',result=$2,updated_at=now() WHERE id=$1 AND generation=$3 AND status='running'",[op.id,state,op.generation]);await c.query("UPDATE outbox_events SET processed_at=now() WHERE id=$1",[op.event_id]);return true})}
  async claimAgentCommand(nodeId:string){return this.tx(async c=>{const r=await c.query(`SELECT * FROM agent_commands WHERE node_id=$1 AND status IN ('queued','leased') AND (status='queued' OR lease_deadline<now()) ORDER BY created_at FOR UPDATE SKIP LOCKED LIMIT 1`,[nodeId]);const command=r.rows[0];if(!command)return null;const leased=(await c.query("UPDATE agent_commands SET status='leased',attempts=attempts+1,lease_deadline=now()+interval '30 seconds',updated_at=now() WHERE id=$1 RETURNING *",[command.id])).rows[0];await c.query("UPDATE operations SET command_attempt=command_attempt+1,lease_deadline=now()+interval '30 seconds',updated_at=now() WHERE id=$1",[leased.operation_id]);return mapCommand(leased)})}
  async recordAgentReceipt(nodeId:string,commandId:string,input:{operationId:string;generation:number;connectionEpoch:number}){const r=await this.pool.query("UPDATE agent_commands SET receipt_at=coalesce(receipt_at,now()),updated_at=now() WHERE id=$1 AND node_id=$2 AND operation_id=$3 AND generation=$4 AND connection_epoch=$5 RETURNING id",[commandId,nodeId,input.operationId,input.generation,input.connectionEpoch]);if(!r.rowCount)throw new DatabaseError("conflict","receipt fence rejected")}
  async recordAgentResult(nodeId:string,commandId:string,input:{operationId:string;endpointId:string;generation:number;connectionEpoch:number;outcome:"succeeded"|"failed"|"unknown";observations:Record<string,unknown>;error?:string|undefined;metadata?:Record<string,unknown>|undefined}){return this.tx(async c=>{const command=(await c.query("SELECT * FROM agent_commands WHERE id=$1 AND node_id=$2 FOR UPDATE",[commandId,nodeId])).rows[0];if(!command)throw new DatabaseError("not_found");const ep=(await c.query("SELECT * FROM endpoints WHERE workspace_id=$1 AND id=$2 FOR UPDATE",[command.workspace_id,input.endpointId])).rows[0];if(command.operation_id!==input.operationId||Number(command.generation)!==input.generation||Number(command.connection_epoch)!==input.connectionEpoch||!ep||ep.node_id!==nodeId||Number(ep.generation)!==input.generation)throw new DatabaseError("conflict","late fencing rejected");if(command.result_at){return}const status=input.outcome==="succeeded"?"succeeded":input.outcome==="failed"?"failed":"running";const result={outcome:input.outcome,observations:input.observations,error:input.error??null,metadata:input.metadata??{}};await c.query("INSERT INTO observations(id,workspace_id,endpoint_id,operation_id,generation,state) VALUES($1,$2,$3,$4,$5,$6)",[randomUUID(),command.workspace_id,input.endpointId,input.operationId,input.generation,input.observations]);await c.query("UPDATE agent_commands SET status=$2,result_at=now(),result=$3,updated_at=now() WHERE id=$1",[commandId,status==="running"?"stale":status,result]);await c.query("UPDATE operations SET status=$2,result=$3,updated_at=now() WHERE id=$1 AND status='running'",[input.operationId,status,result]);await c.query("INSERT INTO audit_events(id,workspace_id,action,resource_type,resource_id,metadata) VALUES($1,$2,$3,'operation',$4,$5)",[randomUUID(),command.workspace_id,`operation.${status}`,input.operationId,result])})}
}

export const migrationSql=await readMigrations();

/** Unit-test adapter only. Production API and worker require PostgresDatabase. */
export class InMemoryDatabase { workspaces:{id:string;name:string}[]=[]; endpoints:Endpoint[]=[]; operations:Operation[]=[]; audits:{id:string;workspaceId:string;action:string;operationId?:string;createdAt:string}[]=[]; outbox:{id:string;workspaceId:string;operationId:string;processedAt:null|string}[]=[]; observations:{id:string;workspaceId:string;endpointId:string;operationId:string;generation:number;state:string;createdAt:string}[]=[];createWorkspace(name:string){const x={id:randomUUID(),name};this.workspaces.push(x);return x}createEndpoint(workspaceId:string,name:string){if(!this.workspaces.some(x=>x.id===workspaceId))throw new Error("not found");const x:Endpoint={id:randomUUID(),workspaceId,name,providerId:"fake",node:null,generation:0,desired:{state:"stopped"},status:{node:"unassigned",runtime:"unknown",provider:"unknown",protocol:"unknown",convergence:"reconciling"}};this.endpoints.push(x);return x}mutateEndpoint(input:{workspaceId:string;endpointId:string;action:Action;expectedGeneration:number;idempotencyKey:string}){const replay=this.operations.find(x=>x.workspaceId===input.workspaceId&&x.endpointId===input.endpointId&&x.idempotencyKey===input.idempotencyKey);if(replay)return{operation:replay,replayed:true};const ep=this.endpoints.find(x=>x.id===input.endpointId&&x.workspaceId===input.workspaceId);if(!ep)throw new Error("not found");if(ep.generation!==input.expectedGeneration)throw new Error("generation conflict");if(this.operations.some(x=>x.endpointId===ep.id&&(x.status==="queued"||x.status==="running")))throw new Error("operation conflict");ep.generation++;ep.desired={state:input.action==="stop"?"stopped":"running"};const operation:Operation={id:randomUUID(),workspaceId:input.workspaceId,endpointId:ep.id,generation:ep.generation,action:input.action,idempotencyKey:input.idempotencyKey,status:"queued",attempts:0,result:null,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),claimedAt:null};this.operations.push(operation);this.audits.push({id:randomUUID(),workspaceId:input.workspaceId,action:"operation.queued",operationId:operation.id,createdAt:new Date().toISOString()});this.outbox.push({id:randomUUID(),workspaceId:input.workspaceId,operationId:operation.id,processedAt:null});return{operation,replayed:false}}}
