import {afterAll,beforeAll,describe,expect,it} from "vitest";
import {execFileSync} from "node:child_process";
import {randomUUID} from "node:crypto";
import {PostgresDatabase} from "@botroost/database";

const container=`botroost-agent-reliability-${process.pid}-${Date.now()}`;
let db:PostgresDatabase;
beforeAll(async()=>{execFileSync("docker",["run","-d","--name",container,"-e","POSTGRES_PASSWORD=postgres","-e","POSTGRES_DB=botroost","-p","127.0.0.1::5432","postgres:16-alpine"]);for(let i=0;i<60;i++){try{execFileSync("docker",["exec",container,"pg_isready","-U","postgres"],{stdio:"ignore"});break}catch{await new Promise(resolve=>setTimeout(resolve,250))}}const port=/:(\d+)$/.exec(execFileSync("docker",["port",container,"5432/tcp"]).toString().trim())?.[1];if(!port)throw new Error("PostgreSQL test port unavailable");db=new PostgresDatabase(`postgresql://postgres:postgres@127.0.0.1:${port}/botroost`);for(let i=0;i<60;i++){try{await db.ping();break}catch{await new Promise(resolve=>setTimeout(resolve,250))}}await db.migrate()},120_000);
afterAll(async()=>{await db?.close();try{execFileSync("docker",["rm","-f",container],{stdio:"ignore"})}catch(error){console.warn("failed to remove PostgreSQL reliability test container",error)}},30_000);
async function fixture(sessionId="session-a"){const workspaceId=randomUUID(),nodeId=randomUUID(),endpointId=randomUUID(),userId=randomUUID();await db.pool.query("INSERT INTO users(id,email,password_hash) VALUES($1,$2,'hash')",[userId,`${userId}@example.test`]);await db.pool.query("INSERT INTO workspaces(id,name) VALUES($1,'test')",[workspaceId]);await db.pool.query("INSERT INTO nodes(id,workspace_id,name,provider,connection_session_id,last_heartbeat_at,connection_epoch) VALUES($1,$2,$3,'fake',$4,now(),1)",[nodeId,workspaceId,`node-${nodeId}`,sessionId]);await db.pool.query("INSERT INTO endpoints(id,workspace_id,node_id,name,provider_id) VALUES($1,$2,$3,$4,'fake')",[endpointId,workspaceId,nodeId,`endpoint-${endpointId}`]);return {workspaceId,nodeId,endpointId,userId,sessionId}}
async function commandFor(f:Awaited<ReturnType<typeof fixture>>){const mutation=await db.mutateEndpoint({workspaceId:f.workspaceId,endpointId:f.endpointId,actorUserId:f.userId,action:"start",expectedGeneration:0,idempotencyKey:randomUUID()});await db.processOne();const command=await db.claimAgentCommand(f.nodeId,f.sessionId);if(!command)throw new Error("command unavailable");return {operationId:mutation.operation.id,command}}
const heartbeat=(sessionId:string,observedAt:string)=>({sessionId,observedAt,runtimes:[]});
describe("agent session reliability on real PostgreSQL",()=>{
it("upgrades a deployed legacy checksum ledger to immutable historical checksums",async()=>{await db.pool.query("UPDATE schema_migrations SET checksum=CASE name WHEN '0001_control_plane.sql' THEN '011b962aa6d1493033b3c42e7d68b5c905d3b2f1f83666761d74af5cf3b5bb3b' WHEN '0002_outbound_agent.sql' THEN '591d69d25129a5be361930030c52f602f2d85042686f5c306d279d5fb6545cfb' ELSE checksum END WHERE name IN ('0001_control_plane.sql','0002_outbound_agent.sql')");await db.migrate();expect((await db.pool.query("SELECT name,checksum FROM schema_migrations WHERE name IN ('0001_control_plane.sql','0002_outbound_agent.sql') ORDER BY name")).rows).toEqual([{name:"0001_control_plane.sql",checksum:"21e94c5207ad27a74cd15a205268b97aab465f2ab162777a053e971192db08b8"},{name:"0002_outbound_agent.sql",checksum:"1723679204313029ac5ce9c82be735e3b6e461dc0062b1a8a7ccd6d142ec5143"}])});
it("uses database time for heartbeat freshness and keeps client time only as metadata",async()=>{const f=await fixture();const before=Date.now();await db.heartbeat(f.nodeId,heartbeat(f.sessionId,"2099-01-01T00:00:00.000Z"));const row=(await db.pool.query("SELECT last_heartbeat_at,heartbeat_metadata FROM nodes WHERE id=$1",[f.nodeId])).rows[0];expect(new Date(row.last_heartbeat_at).getTime()).toBeGreaterThanOrEqual(before-1000);expect(new Date(row.last_heartbeat_at).getUTCFullYear()).not.toBe(2099);expect(row.heartbeat_metadata).toMatchObject({observedAt:"2099-01-01T00:00:00.000Z"})});
it("uses database time rather than API clock to decide session takeover freshness",async()=>{const f=await fixture();const realNow=Date.now;Date.now=()=>realNow()+10*60_000;try{await expect(db.heartbeat(f.nodeId,heartbeat("session-b",new Date().toISOString()))).rejects.toMatchObject({code:"conflict"});expect((await db.pool.query("SELECT connection_session_id,connection_epoch FROM nodes WHERE id=$1",[f.nodeId])).rows[0]).toEqual({connection_session_id:f.sessionId,connection_epoch:"1"})}finally{Date.now=realNow}});
it("atomically fences a stale session takeover and prevents the old session reclaiming ownership",async()=>{const f=await fixture();const {operationId,command}=await commandFor(f);await db.pool.query("UPDATE nodes SET last_heartbeat_at=now()-interval '3 minutes' WHERE id=$1",[f.nodeId]);const takeover=await db.heartbeat(f.nodeId,heartbeat("session-b",new Date().toISOString()));expect(takeover.connectionEpoch).toBe(2);const state=(await db.pool.query("SELECT o.status operation_status,c.status command_status FROM operations o JOIN agent_commands c ON c.operation_id=o.id WHERE o.id=$1",[operationId])).rows[0];expect(state).toEqual({operation_status:"failed",command_status:"stale"});await expect(db.heartbeat(f.nodeId,heartbeat(f.sessionId,new Date().toISOString()))).rejects.toMatchObject({code:"conflict"});await expect(db.claimAgentCommand(f.nodeId,f.sessionId)).rejects.toMatchObject({code:"conflict"});await expect(db.recordAgentReceipt(f.nodeId,command.commandId,{sessionId:f.sessionId,operationId,generation:command.generation,connectionEpoch:command.connectionEpoch})).rejects.toMatchObject({code:"conflict"});expect((await db.pool.query("SELECT connection_session_id,connection_epoch FROM nodes WHERE id=$1",[f.nodeId])).rows[0]).toEqual({connection_session_id:"session-b",connection_epoch:"2"})});
it("serializes concurrent stale-session takeovers so exactly one session wins",async()=>{const f=await fixture();await db.pool.query("UPDATE nodes SET last_heartbeat_at=now()-interval '3 minutes' WHERE id=$1",[f.nodeId]);const results=await Promise.allSettled([db.heartbeat(f.nodeId,heartbeat("session-b",new Date().toISOString())),db.heartbeat(f.nodeId,heartbeat("session-c",new Date().toISOString()))]);expect(results.filter(result=>result.status==="fulfilled")).toHaveLength(1);expect(results.filter(result=>result.status==="rejected")).toHaveLength(1);expect((await db.pool.query("SELECT connection_epoch FROM nodes WHERE id=$1",[f.nodeId])).rows[0].connection_epoch).toBe("2")});
it("keeps unknown outcomes retryable without result_at and accepts a later definite result",async()=>{const f=await fixture();const {operationId,command}=await commandFor(f);const base={sessionId:f.sessionId,operationId,endpointId:f.endpointId,generation:command.generation,connectionEpoch:command.connectionEpoch,observations:{node:"online",runtime:"unknown",provider:"unknown",protocol:"connected",convergence:"unknown"}};await db.recordAgentResult(f.nodeId,command.commandId,{...base,outcome:"unknown"});expect((await db.pool.query("SELECT status,result_at FROM agent_commands WHERE id=$1",[command.commandId])).rows[0]).toEqual({status:"leased",result_at:null});expect((await db.pool.query("SELECT status FROM operations WHERE id=$1",[operationId])).rows[0].status).toBe("running");await db.recordAgentResult(f.nodeId,command.commandId,{...base,outcome:"succeeded",observations:{...base.observations,runtime:"ready",provider:"available",convergence:"converged"}});expect((await db.pool.query("SELECT status,result_at IS NOT NULL done FROM agent_commands WHERE id=$1",[command.commandId])).rows[0]).toEqual({status:"succeeded",done:true});expect((await db.pool.query("SELECT status FROM operations WHERE id=$1",[operationId])).rows[0].status).toBe("succeeded")});
it("terminally fails an operation after the bounded command-attempt budget",async()=>{const f=await fixture();const {operationId,command}=await commandFor(f);await db.pool.query("UPDATE agent_commands SET attempts=5,status='leased',lease_deadline=now()-interval '1 second' WHERE id=$1",[command.commandId]);expect(await db.claimAgentCommand(f.nodeId,f.sessionId)).toBeNull();expect((await db.pool.query("SELECT status FROM agent_commands WHERE id=$1",[command.commandId])).rows[0].status).toBe("failed");expect((await db.pool.query("SELECT status FROM operations WHERE id=$1",[operationId])).rows[0].status).toBe("failed")});
});
